### ISSUE TITLE
[governance.md] several links to GitHub broken

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-docs#1000]
In developers/governance.md several links to GitHub return 404 Not Found.
For example those in the sections:
- #Maintainers
- #Responsibilities

**Comment by Confectrician** [comment]
I don't see any 404 errors.

What i can see is that all links ar working as long as you are logged in and have some kind of access in the openHAB GitHub organisation.

So we would have to find another way to get the linked information or rewrite the whole article in proper way.

Since the docs are not really related to github, we should keep the content clean and remove references taht are not accessible to everyone.

**Comment by mvalla** [comment]
GitHub strangely returns 404 to resources you do not have access to.

I agree to your suggestion to remove links to restricted resources as they do not make any sense for a reader who do not has access to these restricted groups already

**Comment by rhumbertgz** [comment]
In the page [Rules](https://www.openhab.org/docs/configuration/rules-dsl.html) there is also a broken link . 
Defining Rules/File Location/ "The [demo setup](https://www.openhab.org/docs/tutorials/demo.html) ..."

**Comment by blilleike** [comment]
I ended on that 404 too today. I would actually find it usefull to have more information on the ongoing development and who is responsible. 

Is there a reason why e.g. the members of the AC are unknown (like privacy or the way teams work in github)?

**Comment by Confectrician** [comment]
This (the 404 problem) is mainly a thing from github side, which we can't influence.
So the best way (in my opinion) would be to write an explanation as plain text within the docs.

I am not sure how the AC Team is handled within the openHAB GitHub Organisation.

**Comment by pfink** [comment]
@kaikreuzer: Is it intended that the AC pages are not public?

**Comment by kaikreuzer** [comment]
As @Confectrician says - this is how Github handles it, teams are only visible to team members - so any contributor, who is added to the contributors team should be able to see it. And yes, we could add this info to the docs, so that people are not wondering, why they see a 404.

**Comment by Confectrician** [comment]
Then this solution should be realized and we should remove GitHub team links wherever we find them.

**Comment by pfink** [comment]
First sentence of this page is

„To operate with transparency, discussions, minutes, deliberations, project plans, plans for new features, and other artifacts are open, public, and easily accessible.“

What we‘ve got now is the opposite of transparency. Nothing is public, people can neither see who is member of the AC nor follow its discussions or decisions. I don’t think we can leave it like this, this is a communication disaster. We tell people we are so transparent, everything is public and „easy accessible“ and when they want to check it out everything is secret.

**Comment by Confectrician** [comment]
The issue started about "broken links to github" and the conclusion about the initial question was: They are not broken, its just how github handles the teams.
That is for sure not ideal and should be changed (which no one cantradicted here).

Suggestion was:
We should provide a textual explanation in the docs.
So basically that's *exactly* the right direction for increasing the transparency.
Remove misleading links and provide a helpful description.

Everything else from you comment may be right (and i would for sure agree on some point),
but i am not sure if this issue is the right place for it since we only reach a limited number of people here.

**Comment by openhab-5iver** [comment]
> Suggestion was:
> We should provide a textual explanation in the docs.

If this included the process for becoming a member of the openHAB organization in GH, then people would be able to acquire access to the AC discussions. I'm not sure what that process is, or if there are requirements for becoming a member, like being a contributor.

**Comment by pfink** [comment]
To be honest, in case we don't change the visibility of the AC to public somehow, I think we should completely remove the AC section from the docs. If it's something that is only visible and relevant to openHAB Organization Members, then the documentation should also only be visible to those members.
