### ISSUE TITLE
What has happened to the Concepts / Categories page?

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-docs#1061]
We have nearly five links to it (https://www.openhab.org/docs/concepts/categories.html) in the [Binding Definitions](https://www.openhab.org/docs/developer/bindings/thing-xml.html#channel-categories) section and maybe much more in other places. But we only get a 404 when navigating to the link.

Why did we exclude it during creation? Any specific reason? What can be done to include it again?

https://github.com/openhab/openhab-docs/blob/87a37fba0d05575f4c1c79c5f5a3be2f4b4e11a7/.vuepress/process_main_docs.rb#L25-L30

**Comment by ghys** [comment]
The reason was technical: the [original page](https://github.com/eclipse/smarthome/blob/master/docs/documentation/concepts/categories.md) in question in the ESH docs includes Jekyll-specific syntax (for..in loops) to generate the tables from external site data. That syntax is not compatible with VuePress - the technology used by the website; it can be done but needed a rewrite. Also the info (and the category concept) is arguably useless for end users and similar to what they can find on https://www.openhab.org/docs/configuration/iconsets/classic/ and/or the semantics.

Finally, the Concepts section itself (or big chunks of it) was eventually due to a more user-friendly rewrite anyways, because a lot of the info in it is irrelevant to them and should probably be moved to the developer section. That specific page could be restored there, maybe in a static fashion i.e. without the tables generation.

**Comment by Confectrician** [comment]
IIRC we have talked about that ages ago shortly after reintegrating ESH and reintegrating the smarthome docs too.
But i am not sure anymore why we have choosen this way.

**Comment by martinvw** [comment]
I'm also missing this page :-)

For the reference the very old page: https://docs.openhab.org/v2.2/concepts/categories.html

**Comment by Confectrician** [comment]
Ok. So i had a look again (filed a wrong duplicated issue while i was shortly confused...) and now i am back on track.

Should be no problem to rewrite the page without those loops.
But maybe we should then move it to the developers area directly.
