### ISSUE TITLE
openHAB 3 Documentation  - ToDo

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#1133]
# Goal

This issue is meant as a To-Do list for tasks that we have to accomplish for the openHAB 3 release.
This is mainly adressed to the internal parts of this repository and the website appearance.
External content can be fetched from the OH3 branches of the corresponding repositories with some effort.
The contributors of those repositories should check and improve contents themselves in the corresponding repositories.

## Accomplished (so far)

> Concepts => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744047078
> Installation Guide => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744047092
> Configuration Guide => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744047100
> Interfaces and Ecosystem => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744054946
> Administration Guide => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744047105
> Developer Guide/Appendix => https://github.com/openhab/openhab-docs/issues/1310#issuecomment-744049193

**Comment by ghys** [comment]
I would say let's create a subdomain like v3.openhab.org, dev.openhab.org or next.openhab.org for the 3.0 docs and deploy a site with its own workflow. The main openhab.org would for now display the 2.5.x docs, maybe with a link to switch to the "next version" site. The home page's "hero" image would be due for a change as well when 3.0 is released, maybe we can also prepare a v3 demo server in the meantime, depending on the burden of maintaining it.

Also, eventually I'd like to revisit the version switcher widget which appears on each page and abandon the principle of staying on the "same" page when switching versions - we overlooked how quickly it can become a PITA when the structure changes (and I suppose it will change significantly for 3.0) and we end up with a lot of dead links. I'd rather put a combobox in the left column with a list of versions and navigate back to the intro page (/docs/) when switching.

**Comment by kaikreuzer** [comment]
Sounds good to me. Would you create a new site in Netlify? I would then add an dns entry for a sub-domain (next.openhab.org sounds good, although I am fine with any other option as well).

**Comment by Confectrician** [comment]
I would vote for `next.openhab.org` too. Sounds catchy.

**Comment by bwosborne2** [comment]
If you use v3.openhab.org that will be obvious and "future-proof" whenever v4 arrives. You could even just redirect the main page to the latest version.

**Comment by ghys** [comment]
Updates - There are now parallel processes for 2.5.x and 3.x docs and websites:
| | v2.x | v3 |
|-|-------------|-------------|
| General docs branch | `2.5.x` (default) | `master` |
| Final docs branch (w/ addons) | `final-2.5.x` | `final` |
| Current docs preview URL | https://openhab-docs-preview.netlify.com | https://master--openhab-docs-preview.netlify.com |
| Jenkins jobs (view) | [Documentation (2.5.x)](https://ci.openhab.org/view/Documentation%20(2.5.x)/) | [Documentation (3.x)](https://ci.openhab.org/view/Documentation%20(3.x)/) |
| Gather external docs Jenkins job | [gather-external-docs-v2](https://ci.openhab.org/view/Documentation%20(2.5.x)/job/gather-external-docs-v2/) | TODO |
| Merge docs Jenkins job | [merge-docs-v2](https://ci.openhab.org/view/Documentation%20(2.5.x)/job/merge-docs-v2/) | TODO |
| Redeploy website Jenkins job | [redeploy-website-v2](https://ci.openhab.org/view/Documentation%20(2.5.x)/job/redeploy-website-v2/) | TODO |
| Website branch | `v2` (default) | `master` |
| Website deploy URL | https://www.openhab.org/ | https://master--openhab-website.netlify.com (1) |

(1) @kaikreuzer you might want to configure alias(es) as discussed above and/or enable CF for this one. The black "jumbotron" background is intentional, it's meant to distinguish the v3 website while it's not the production one. The download page has been simplified for v3 for the time being (and the production website only offers v2 install instructions & links).

Notes:
- all relevant changes to the `2.5.x`/`v2` branches have to be cherry-picked and added to the `master` branches too. I have changed the base branches and added a reminder to all currently PRs in this repo. Please double-check the base branch when merging PRs.
- we probably won't alter the process for 2.5.x but the process for 3.x is open to changes and improvements since the branches may diverge without breaking the 2.5.x process (everything being duplicated).

**Comment by Confectrician** [comment]
Thanks for pushing this forward Yannick 👍

**Comment by wborn** [comment]
I've created some issues for OH3 documentation updates (#1161, #1162, #1163). Is it already a good idea to create PRs to solve these?

**Comment by ghys** [comment]
@wborn you can but you will only see the changes in the preview site - the Jenkins jobs to prepare the website deployment are not there yet.
Also the website for v3 (https://master--openhab-website.netlify.com/) now runs a more recent version of VuePress, I still have to adapt the preview. It shouldn't matter though.

**Comment by bwosborne2** [comment]
There should at least be documentation warning that OH 3 is not yet usable. We are seeing quite a few new users blindly trying to run OH3.

**Comment by ghys** [comment]
@bwosborne2 I noticed, that's why the main website download page https://www.openhab.org/download/ doesn't mention the 3.0.0-SNAPSHOT versions anymore (it used to because of a snafu), and the upcoming new website currently has a warning: https://master--openhab-website.netlify.com/download/
to discourage users from using OH3 in production yet.

**Comment by kaikreuzer** [comment]
> (1) @kaikreuzer you might want to configure alias(es) as discussed above and/or enable CF for this one.

I've created a CNAME entry, but https://next.openhab.org/ now shows a "not found". Any idea, why?

**Comment by bwosborne2** [comment]
I am getting a WEB PAGE that says "Not Found". That is the default index page on the server.

**Comment by kaikreuzer** [comment]
nslookup gives me different IP addresses:
```
Name:	next.openhab.org
Address: 104.24.114.50

Name:	master--openhab-website.netlify.com
Address: 167.99.137.12
```
Maybe I need to give DNS time to propagate? Looks weird as this subdomain didn't exist before...

**Comment by bwosborne2** [comment]
Hmmm.
Name:    next.openhab.org
Addresses:  146.112.239.210
          146.112.43.224
          146.112.43.233
          146.112.43.47
          146.112.43.13
          146.112.43.225
          146.112.43.132
          146.112.43.183
          146.112.43.185
          146.112.43.185
          146.112.43.47
          146.112.43.225
          146.112.239.210
          146.112.43.233
          146.112.43.224
          146.112.43.183
          146.112.43.132
          146.112.43.13

**Comment by ghys** [comment]
>Name:	next.openhab.org
>Address: 104.24.114.50

>Name:	master--openhab-website.netlify.com
>Address: 167.99.137.12

Seems legit since the first is CloudFlare and the second is Netlify.
I'm not sure about the "Not Found"...

**Comment by bwosborne2** [comment]
Is there something needed in CloudFlare to point to the new content?

**Comment by ghys** [comment]
>I've created a CNAME entry, but https://next.openhab.org/ now shows a "not found". Any idea, why?

Actually that's probably it, either you do a CNAME or proxy through CloudFlare ;)

**Comment by bwosborne2** [comment]
It's working for me now.

**Comment by kaikreuzer** [comment]
No, I did it the same way as for www.openhab.org. The issue is that the Netlify server(s) don't know what site they should serve as they are not aware of next.openhab.org.

@ghys I have now added it to https://app.netlify.com/sites/openhab-website/settings/domain#domains, but this means that it is considered as an alias for the main deployment, so that we only see the v2 of the website. Would we have to set up v3 as a separate project?

**Comment by bwosborne2** [comment]
OK just trying to he helpful.

**Comment by kaikreuzer** [comment]
@bwosborne2 The "no" was actually in response to @ghys, you just happened to have also posted meanwhile. ;-) Your efforts are certainly appreciated!

**Comment by ghys** [comment]
> No, I did it the same way as for www.openhab.org. The issue is that the Netlify server(s) don't know what site they should serve as they are not aware of next.openhab.org.

I thought CloudFlare was making requests with the "internal" URL (master--openhab-website.netlify.com) so that the Netlify server couldn't tell what was the "correct" URL, and that the "Domains" screens on the Netlify console was irrelevant since we're not serving the site under the primary domain with them. That's probably not the case.
I think creating a new, separate site for next.openhab.org will work - if they let us have multiple sites for the same repo... Trying that now.

**Comment by ghys** [comment]
Okay, it worked right away 👍

**Comment by bwosborne2** [comment]
Great! 
One content note. The page says "No Cloud Required" but OpenHABian, the recommended installation requires an Internet connection to install and install any bindings. It does not support the addons package. Many people equate the Internet and Cloud because usually without Internet access there is no Cloud.

**Comment by ghys** [comment]
No that means master--openhab-website.netlify.com is not updated, the URL now is next.openhab.org and internally it's another site.

"No cloud required" in this case tries to make the point that you're not required to signup to an online service.

**Comment by bwosborne2** [comment]
While the **developer** community understands this I believe much of the **user** community does not.  
Are we aiming at developers or users? I realize there is some overlap but I believe there are now more users than developers.

**Comment by kaikreuzer** [comment]
> Okay, it worked right away 👍

Excellent!

> While the developer community understands this I believe much of the user community does not.

I think even 95% of users understand that for software installation from the Internet, they will need the Internet... But I think this discussion is going off-topic, so let's end that one here :-) .

**Comment by Confectrician** [comment]
Hi all,

I have updeted the firt post with a list of articles that need some attention, before the release of openHAB 3.
I have notes with more details for the single articles and will extend the todos further with some mor post updates.

**Comment by Confectrician** [comment]
Another update:

I have added all "Todo-Elements" we discussed already.
This list does not aim to be complete at the current state.

If you find additional places where the docs need to be changed for OH3 i would encourage you to report them here.

Also feel free to pick up parts of this list for improving them.
If you are interested in improving a article we can track this in a separate issue or WIP PR

**Comment by rkoshak** [comment]
OK, looking at this list of todo again with fresh eyes and with OH 3 being much closer I've a few ideas. Don't know how feasible they are to accomplish before the OH 3 release.

1. I think we should separate the "how rules are added through MainUI" from the Rules DSL docs. That content will be basically applicable to all the supported languages. Once you replace all the stuff referencing triggers and structure of rules files and such with generic descriptions applicable to all the MainUI languages there isn't that much left that's language specific: the names of the implicit variables, how to call Actions, reference to how to write in the language, etc.

2. We should include some reference and example in all the languages that OH ships with. Right now that means Rules DSL, JavaScript, and Blockly. There might be a way to include all three in the same docs with tabs to switch between the examples, especially given 1.

3. The JSR223 docs are a great reference for those users who want a really low level explanation for what's happening under the covers and for those who will be developing rules libraries. It also documents what openHAB core services are available and how to access them. But I don't think it's needed for the average everyday users. The discussion about the JSON format of the rules and rule templates and stuff is definitely not something the average user needs to worry about. Maybe they should go to the developers section of the docs?

4. Since other languages are supported via add-ons, I would expect the readmes for those add-ons to cover those languages. It doesn't feel right to include them in the main docs, though we made an exception for integrations with GA and Alexa so maybe we should make one here too. I'd love to see some Groovy docs honestly. 

5. Obviously we need to keep the existing Rules DSL docs around too because they show how to build .rules files. Do we need an equivalent for JavaScript .js rules files too? Since the helper libraries will be add-ons I suppose we need to show how to do it the hard way.

My main focus is on the Getting Started Tutorial right  now (you can check off the "remove the 1.x migration tutorial" task. Still looking like I can have an initial version posted by Monday. We can probably steal some of that content for 1. also.

**Comment by Confectrician** [comment]
I would prefer some missing information over wrong information and that's what my focus is on currently.
I would have a second look at your sugggestions when the "small changes" have been accomplished already and see if we can include some of them already while updating the articles.

**Comment by kaikreuzer** [comment]
I agree with @Confectrician - better use the chance to clean up and remove things that are not correct (anymore). Content is still available on the 2.5 docs (and in git history), so it can be worked on and reintegrated at a later point as well.

**Comment by mstormi** [comment]
FWIW most users will not really be _starting_ with OH3 but will 'carry forward' their knowledge of the way things were done in OH2 even if they start with their OH3 install from scratch.

So in the parts I have changed so far I added paragraphs using
::: tip note to OH2 users
text-whats-changing
:::

where there were significant changes in 2->3.

**Comment by bwosborne2** [comment]
> FWIW most users will not really be _starting_ with OH3

I am not sure we can assume that. We are already seeing a few start with OH3 and, since OH3 will be more & more emphasized and OH2 deprecated I would expect that maybe half of new users would be starting with OH3.

**Comment by mstormi** [comment]
You miss the point, Bruce. We got tens of thousands of OH2 users.
They *all* will carry their knowledge forward, many will not even read the release notes then fail miserably on breaking changes.

**Comment by Confectrician** [comment]
Hey @openhab/contributors this is also a shoutout to all of you.

> First of all thanks for contributing and improving openHAB

We need your help to have a look at other places of documentation like the openhab-addons repo, the openhabian repository, the openhab-android repo, ....

I would like to encourage all of you to check your own bindings, places where you are active and have a look for outdated informations.

### Those are mainly small things like
- The wording `openHAB 2`
- References to a deprecated UI like `Paper UI` or `Homebuilder`
- Examples with outdated paths like `etc\openhab2`
- Screenshots from an outdated UI in your docs
- openHAB 1.x references
- ...

(The list goes on. Maybe you know the outdated parts better then me already in your special case.)

Please check your known repos/doc parts for such things and fix them right away.
**The more people help, the less effort is needed for everyone.**

Thanks in advance for your efforts and for making openHAB better step by step. 👍

**Comment by bwosborne2** [comment]
> openhab-addons repo,

Aren't those docs generated in the addons themselves? 
I know I helped with the Z-Wave Thing documentation when we moved database servers.

**Comment by Confectrician** [comment]
> Aren't those docs generated in the addons themselves?

That's why am encouraging addon contributors to check there docs over there for outdated parts too with the post above.

**Comment by bwosborne2** [comment]
> encouraging addon contributor

Perhaps there should be a separate issue with a list targeting all addons should be in that repo? They would not necessarily look in this repo.

**Comment by Confectrician** [comment]
Feel free to add an issue there.
So far I have mentioned the whole contributors team in that post and also asked some of the other maintainers to spread the word a bit.
The more people we can reach, the faster we have done all the work. :)

**Comment by bwosborne2** [comment]
> Feel free to add an issue there.

I am a lowly user without the time to "herd cats" LOL 

https://www.urbandictionary.com/define.php?term=herding%20cats

**Comment by Confectrician** [comment]
And i am focussing on this repo for now. So spread the word it is.

**Comment by bgilmer77** [comment]
> You miss the point, Bruce. We got tens of thousands of OH2 users.
> They _all_ will carry their knowledge forward, many will not even read the release notes then fail miserably on breaking changes.

Have not had time to contribute much over the last year, so forgive me if this is already covered.  Will there be a single list of "breaking changes", perhaps in the OH3 release notes?  This might be one place people would look, especially if their OH2 to OH3 changeover does not go well.  It might also give those supporting OH3 issues in the Community a single document to point people to when the inevitable flood of "this stopped working when I moved to OH3" questions start coming in.

**Comment by lolodomo** [comment]
The doc of few bindings are mentioning condole commands. They have to be updated because prefix was smarthome while it is now openHAB.

**Comment by bwosborne2** [comment]
I just opened an issue for a bad & incorrect link for Z-Wave.  since that is generated as part of their database export, Chris will fix it.
Otherwise, Z-Wave looks good to me.

**Comment by JueBag** [comment]
I'm presently checking the Tankerkoenig addon and have two questions:
-where would the things status descriptions be visible on OH3? If the webservice of tankerkoenig got banned the status description of this bridge would give hints for the reason. It used to be shown on PaperUI.
-Should links to other documentation pages ( in my case [ephemeris action](https://www.openhab.org/docs/configuration/actions.html#ephemeris) be kept or changed to "next..."?

**Comment by rkoshak** [comment]
Oh, one important thing that needs to be updated in the Rule page is a rewrite of the DateTime section under Manipulating Item States. All the content there is Joda DateTime Based and need to be updated for ZonedDateTime.

**Comment by kaikreuzer** [comment]
> Will there be a single list of "breaking changes", perhaps in the OH3 release notes?

Yes, we were gathering such things on https://github.com/openhab/openhab-distro/wiki/Breaking-Changes-in-openHAB-3 and I planned to reference this content in the release notes then (and also add a link in the update script). @Confectrician & @rkoshak - also for your information, in case you weren't aware of that page yet. It is not meant to replace documentation, but rather be a "short reference list" of what to look out for when migrating. If we can add links to according places in the documentation, it would be ideal.

>  All the content there is Joda DateTime Based and need to be updated for ZonedDateTime.

@rkoshak I tried to cover this already with https://github.com/openhab/openhab-docs/pull/1294. Let me know if you think there is anything crucial missing. Wrt migration guide, it'd be probably very helpful for users to have a before/after comparison for various time expressions in rules.

**Comment by Confectrician** [comment]
> -where would the things status descriptions be visible on OH3?

@ghys correct me if i am wrong please

The thing status will be shown in the things area of the new ui.
![image](https://user-images.githubusercontent.com/7161177/101981479-7e1f1480-3c6d-11eb-8dc0-15422c62867f.png)

So generally an additional message should be shown there too

**Comment by mstormi** [comment]
@Confectrician when will you put this live ? There's already several OH3 users looking for information that would benefit today.

On a sidenote, shouldn't we have some native speaker proofread at least the major index pages before release?
@rkoshak Rich maybe ? Or is that going to be too embarassing for us Germans :duck: ? [_ok **den** verstehen wohl nur Deutsche_]

And anyone willing to rework the very top entry page ? As @ghys noted at times that's too much "motivational talk".

**Comment by bwosborne2** [comment]
Just a quick look at the firs link for Windows. I suggest updating some of the screen captures. I see Karaf captures from version 2.0.0 and I know at least the header text has changed.

In Windows does the Karaf console require the password `habopen` when launching?

**Comment by markus7017** [comment]
fyi: @fwolter is reviewing PR #9390, which updates the documentation for the Shelly binding

One aspect is open: The doc also include a sample how to implement log filtering. Due to the fact that the config format has changed (cfg to xml), this is specific for version 2. I'm not familar with version 3 format, maybe somebody else could help.[ I created a post in the community](https://community.openhab.org/t/log-filtering-in-oh-3/110376).

The documentation for the MagentaTV binding has already been converted with regards to console commands openhab:xxx vs. smarthome:xxx - looks good.

The documentation for the GREE binding includes "PaperUI:Configuration:System:Network Settings". 
@Confectrician: could you fix this or do I need to create a PR.

**Comment by rkoshak** [comment]
You'll only have to look at a few of my posts on the forum to realize I'm an absolutely terrible editor. But I can do my best. It's the end of the year crunch for me though and I'm not able to spend as much time as I expected. I'm way behind where I want to be on the getting started tutorial.

**Comment by mstormi** [comment]
> On a sidenote, shouldn't we have some native speaker proofread at least the major index pages before release?

@ecdye Ethan would you be willing to take a last minute shot ?

**Comment by psmedley** [comment]
If Ethan can't, I should be able to.

Cheers,

Paul

**Comment by ecdye** [comment]
I can't this weekend, I'm going to be busy. I'll take a look at them when I can though.

**Comment by bobadair** [comment]
I did a proofread of the configuration index page, and submitted PR #1323 with some edits. However, I later noticed that there are some other open PRs that involve this file, so there may end up being some merge conflicts.

What are the most important file to proofread right now?

**Comment by mstormi** [comment]
> submitted PR #1323 with some edits.

I've closed my PR so it does no longer interfere with yours

> What are the most important files to proofread right now?

`*/index.md`, i.e. the overview/index pages of all the chapters.

**Comment by Confectrician** [comment]
Hi all,

Sorry for the late answerr but i had t ofinish some things on work first to end the work year and start holidays.

Some comments to the posts from last 3 days:

Proofreading:
Due to limited time we have no native speaker planned for proofreading.
We have some ideas for the future for this but that won't be ready for OH3 release.

But as @mstormi says any volunteery proofreading is welcome. :)

Live:
I have to move this question to @ghys.
Everything merged here should be live unt the next.openhab.org docs already.
We had some trouble with our website/docs build and disabled it for some days but that should be fixed already.

So the needed tas should be a switch from our main homepage to the new contents of next.openhab.org.
But that's yannicks playground.

@bwosborne2 
The screens are part of the todo list.
Everyone is free to get involved and work on parts of it.

From what i know the openhab console (please note that karaf as name should not be used anywhere anymore) should need habopen as a password on every system.

@fwolter 
Would be nice if you can organise changes in the addon repo yourself.
I will have to focus on this repo next days.


@bobadair and @mstormi i will check the PRs today.

**Comment by Confectrician** [comment]
I have worked trough the Pull Requests and we have merged everything except the work in progress tutorial by @rkoshak.
Most to-do's that are left are located in the configuration parts.

I will have a lookup now for the amount of needed changes and will do all small changes in a bulk pull request.
Any help for getting the existing docs to the finish line now is appreciated.
Please give a quick reply here, if you would be able to help on one specific article to spread the needed work.
I would then leave it out from my bulk imporvements.

**Comment by BClark09** [comment]
Hi @Confectrician,

Added a PR with my suggestions for change in the Linux installation docs.

**Comment by Confectrician** [comment]
Quick merge. :) Thanks for proofreading this article.

**Comment by mstormi** [comment]
Ouch, that now was pretty interesting to me as well as we've been using those old repo URLs in openHABian until now.
Ben could you please confirm that the stable/release repo will be
`repo="deb https://dl.bintray.com/openhab/apt-repo2 stable main"`

**Comment by bobadair** [comment]
I submitted PR #1331 for administration/index.md which has already been merged.
I just proofread concepts/index.md and didn't think it required any edits.
I'm now proofreading installation/index.md.

Is addons/index.md ever linked to, or should it be removed? I don't see that content showing up anywhere in the docs.

**Comment by Confectrician** [comment]
> Is addons/index.md ever linked to, or should it be removed? I don't see that content showing up anywhere in the docs.

I had that question in mind too.
I think @ghys  rewrote this for the new addons page we introduced some time ago.
We can remove it later if it really isn't linked anywhere and not useful anymore..

**Comment by bobadair** [comment]
I've submitted another two PRs after proofreading:
#1335 for installation/index.md
#1336 for developers/index.md

**Comment by Confectrician** [comment]
I have updated the first posting again.
We have only few tasks left and not all are urgent for the release tomorrow.
I will try to get the Tutorial merged today with its latest progress and add some pages with links to the corresponding Wiki forum threads for the advanced topics.

**Comment by Confectrician** [comment]
Hi all,

I have (friendly :P) taken over the pull request from @rkoshak #1304.
We have got a working Preview now after some structural changes.
https://deploy-preview-1304--openhab-docs-preview.netlify.app/docs/tutorial/

Could one or two of you do me a favor and proofread it?

Please be aware of missing articles so far.
We won't get everything live for the release,, but i want to have the current version in the website and add some links to the wiki pages until we have full article replacements.

Please use the pull request for any improvement sufggestions or corrections.

Thanks.

**Comment by bwosborne2** [comment]
I believe there are some steps before creating the Admin user. 

Offhand I remember a wizard to set the regional settings as well as an option to add bindings.

**Comment by Confectrician** [comment]
> Please use the pull request for any improvement sufggestions or corrections.

This issue already has many comments and is hard to overview.

**Comment by ghys** [comment]
> I believe there are some steps before creating the Admin user.
> Offhand I remember a wizard to set the regional settings as well as an option to add bindings.

No you create the admin user _before_ you get to the wizard (you wouldn't be allowed to make such changes anyways without being authorized).

But I'm realizing some parts of the tutorial were made before the setup wizard was implemented, and screenshots are outdated, there's been changes to many screens since then, so they could use an update.

**Comment by bobadair** [comment]
> Please use the pull request for any improvement suggestions or corrections.

I started proof reading the tutorial files. I assume that pull requests should be made to the rkoshak/openhab-docs repo getting_started branch. I just submitted one there with some minor edits to index.md.

**Comment by Confectrician** [comment]
Ok i have setup a new ubuntu vm, did a fresh ih3 install and added some (german, sorry) setup wizard screenshots for now.

**Comment by Confectrician** [comment]
Hey @bobadair,

Do you want to proofread something to the pr (are are you already preparing something)?
If not yet started i would suggest to merge the pr as is and add improvements to the docs repo directly afterwards.

**Comment by bobadair** [comment]
Great! I see you merged #1304. So I'll submit any further PRs (assuming I have time for some later today) directly to this repo.

**Comment by mstormi** [comment]
I saw it's live now. There's a wrong line in https://www.openhab.org/docs/configuration/#versatility but I don't know how to change it now.
It's the last line of the blue info tip box: the option is only for items from .items files , but not for Things and .things files.
@Confectrician could you please manually correct that

**Comment by Confectrician** [comment]
Should be here:
https://github.com/openhab/openhab-docs/blob/main/configuration/index.md

I can take carr but i am working on some wrong things in the beginner tutorial now first.
If you find time earlier you can give it a try.

**Comment by mstormi** [comment]
https://github.com/openhab/openhab-docs/pull/1355

**Comment by bobadair** [comment]
I finished proofreading the Getting Started tutorial and submitted another couple of PRs with minor edits. But it's important to note that I was only looking at wording, punctuation, etc. I did NOT attempt to verify the technical content. Not that I'm unwilling to help there, but there wasn't time before the release since I'm not yet familiar enough with the OH3 UI to quickly recognize errors.

**Comment by Confectrician** [comment]
Thanks @bobadair 

The way you did it was exactly what we needed here.
If somethings wrong on the content side still, users will tell us very quickly. ;)

NAtive english proofreading is one big gap we have to fill on long term for the documentation.

**Comment by bobadair** [comment]
Since I'm from the US, my friends from the UK disagree that I'm a native English speaker :-) but I'm always willing to do a bit of proofreading if you point me in the right direction.

**Comment by Confectrician** [comment]
Hi all,

I think this issue has enough postings now.
With #1346 as follow up in place, we have accomplished all "needed" changes for openHAB 3.
I am still not satisfied with everything, but we can go on with improving things regularly with issues and pull requests now.
No collection issue needed anymore.

Thanks to all of you who have helped out and contributed or gave feedback.
Your help is much appreciated and of course it will be appreciated in the future too.

Have some nice christmas days and a good start in year 2021.

BR
Jerome

**Comment by mstormi** [comment]
We still a medium to track TODOs, don't we ?
[I got word](https://community.openhab.org/t/nginx-unauthorized-api-request-with-un-pw-prompt-oh3-openhabian/111199/4)  that https://www.openhab.org/docs/installation/security.html#running-openhab-behind-a-reverse-proxy is not up to date with OH3

**Comment by Confectrician** [comment]
Stated above
> but we can go on with improving things regularly with issues and pull requests now

We're in the docs repo, thats what issues are for here.

To your special topic:
https://community.openhab.org/t/nginx-unauthorized-api-request-with-un-pw-prompt-oh3-openhabian/111199/10?u=confectrician
