### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#1169]
How can I include a toc? The page configuration/sitemaps.md has the following code:
```
{::options toc_levels="2..4"/}

- TOC
{:toc}
```

What does that mean? Do I need all of that or is `{:toc}` enough?

**Comment by ghys** [comment]
This is the old syntax (it's partly converted by a script to work but shouldn't be used anymore), now it's `[[toc]]`

https://vuepress.vuejs.org/guide/markdown.html#table-of-contents

**Comment by mueller-ma** [comment]
Thanks! I added a toc to the Android app page yesterday. How long does it usually take to build the site?

**Comment by ghys** [comment]
Usually it's done automatically by this job: https://ci.openhab.org/job/redeploy-website-v2/, it normally occurs after the docs are gathered for a new distribution build - which itself occurs after a merge on the addons or webui repos -, unfortunately since the Android app is not part of the distribution the changes to your docs are simply picked up whenever a distro snapshot is built (last was was 11h ago).

Then it has to trigger the website redeployment and that wasn't even working because of the recent branch moves for the v3 website... The good news is, that part is fixed at least and the site is now up-to-date: https://www.openhab.org/docs/apps/android.html
