### ISSUE TITLE
Add a way to mark bindings obsolete

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-docs#1200]
Currently if there is a oh2 binding with the same name as the oh1 binding, the oh1 binding will include an "OBSOLETE BINDING" message at the beginning of the documentation. An example of this the **astro** binding.  This request is to add the ability to mark oh1 bindings that have been replaced by a oh2 binding with a different name.  An example of one is the oh1 **insteonplm** binding has been replaced with **insteon**. There are many other bindings that also fall in this category and some are documented at https://github.com/openhab/openhab-addons/issues/6179

**Comment by openhab-5iver** [comment]
All OH1 bindings have been removed in OH 3.0.

**Comment by ghys** [comment]
True but there could be a valid need to flag a binding as deprecated and replaced by another - not only OH1 bindings but a generic way of specifying deprecation messages. We should define some frontmatter attributes to be put on an add-on README like (not an actual example):
```
replaced_by: insteon
```
or
```
deprecated: true
deprecation_reason: This binding doesn't work anymore because the API has been shut down.
```
then the script processing these would behave accordingly.

**Comment by Confectrician** [comment]
@ghys 

I would love to have all 3 parameters in place. :)

We could add a special deprecated reason if needed and otherwise use a standard phrase or a "standard replaced by phrase"

**Comment by robnielsen** [comment]
Good suggestions @ghys, I changed the subject to make it more generic

**Comment by Hilbrand** [comment]
The reason this is not marked obsolete is at least because the `insteonplm1` is not moved to the legacy feature.xml in the openhab-addons1 repository. This is convention when a binding has been replaced. Although I don't know if the renaming of the binding might cause an issue in displaying the message too.
However there is another problem with that convention because there are bindings that have been replaced, but are neither in legacy or standard feature because they were never confirmed to work with OH 2. (See https://github.com/openhab/openhab1-addons/issues/5781). 
That having said. It's certainly useful to add an option to mark bindings obsolete as suggested.

**Comment by Confectrician** [comment]
I am not sure, if we shoudl invest much time into this currently.
With openHAB 3 in place we have a stable addon base currently.

We can go for a solution in the future, if there should be a need for ist.
