### ISSUE TITLE
Recommend Wireguard for VPN?

### ISSUE THREAD

**Issue by TRSx80** [openhab/openhab-docs#1242]
I was just looking at https://www.openhab.org/docs/installation/security.html#vpn-connection where it says (near the top of page):
> The most secure option is probably to create a VPN connection to your home network. Doing so will allow you to access your openHAB instance in the same way as if you were at home. There are many different solutions for VPN, so we cannot give any specific advice here, what to use and how to set in up.

Then pretty much the whole rest of the page is dedicated to describing how to install nginx, set up SSL certificates, etc.  I got a headache just skimming over that, and I am a GNU/Linux and Emacs user that prefers the command line and self hosts all my own "cloud" services.  And yes I have set up my own certificates, I even have them auto-renewing by now at home as well as on hosting providers (using acme.sh).

Anyway, all of that is a nightmare compared to [Wireguard](https://www.wireguard.com/), which is vastly simpler to set up, and arguably more secure.  Even Linus Torvalds himself had nice things to say about it (and you know how rare that is, lol).

I didn't think this was a controversial position really, although I did get into it with @rkoshak in a forum thread once, at that time I recall him thinking it was "untested", etc.  Not sure if he changed his mind in the meantime, but anyway I thought that I would make a thread here to discuss the issue.  Or should I make a forum post?  Here seemed like the better place to me.

If it's not controversial, I would be happy to submit a PR with a small edit adding Wireguard as a suggestion.  Which would likely be worlds better than doing nothing, which is what most people are probably doing in reality, rather than go through all the hassle of setting up a reverse proxy, certificates, registering a domain, etc...  And thereby helping the majority of users to increase security by making it much more accessible.

**Comment by bgilmer77** [comment]
SoftEther is another tested and relatively easy VPN to install.  So should we leave it as is, saying you can install a VPN and there are lots of options to choose from, or should we add a few specific VPN systems to help people along?

**Comment by rkoshak** [comment]
At the time is was untested. Even the Wireguard site said so. It has since received more third party audits and the like. I don't have a problem with WireGuard as much as taking on the responsibility to make such a recommendation in the first place. 

There are tons of VPN solutions, some of which are just as easy to set up and use as Wireguard. Why should we take on the responsibility to make a specific recommendation and continue to keep up with the changing state of VPN software and approaches. Making little recommendations like these are simple enough but they:

- become controversial as every user pushes their recommendation of choice
- come with a long term commitment to keep up with the recommendation and change it as the world changes
- an expectation that we would generate a tutorial for how to set it up.

Just look at the thread and arguments that erupted when we discussed the very uncontroversial recommendation to "use what you have or, if you don't have anything use an RPi 3". I can't imagine a more milquetoast recommendation yet the thread erupted into argument and ran for hundreds of posts. 

My recommendation would be if you want to recommend Wireguard, write a tutorial on the forum. I don't think it is worth making any stronger recommendation than that. I could see maybe adding a *list* of VPN options with a comment saying that the list isn't an endorsement of any of them nor is it intended to be complete. 

SoftEther, PiVPN, Algo, wizards built into many WiFi routers/gateways including DD-WRT, pfSense, Tangled, and OPNsense, etc. are all options simple and relatively easy to set up options. 

And the best choice for any individual user, and the choice whether to use a VPN at all, is something that is going to be unique to each individual user. For example, I run pfSense. It's *way* easier for me to use the built in wizrds to set up OpenVPN than it would be to install Wireguard somewhere. DD-WRT users would find the same. PiVPN is a appliance requiring very minimal configuration. Algo puts a wireguard server in a cloud VPS to connect to. From a security perspective that's be much safer than hosting it yourself as you can avoid punching a hole in your firewall.  There are simply too many variables like these to make a blanket recommendation, IMO.

**Comment by Confectrician** [comment]
>I could see maybe adding a list of VPN options with a comment saying that the list isn't an endorsement of any of them nor is it intended to be complete.

I would agree with this statement.

We can say something about security at all and that vpn at all is a good choice.
And we could extend that with a list of possible solutions, so a unexpirienced user has some buzzwords for an own research.

**Comment by TRSx80** [comment]
I suppose I can appreciate the hesitance of the project to make any sort of "official" recommendation, given it is a "security" issue, in addition to all the other potential issues mentioned...

However I would point out that lumping Wireguard in the same basket with all of these other traditional VPN solutions is a quite incorrect assumption, as Wireguard works *very* differently from the others.

For example, it completely eschews AES encryption, making it ideal for the sort of embedded devices (without hardware AES support) that OpenHAB often is run on, making it a much faster throughput option in practice.

Config could not be simpler, it is just a few lines of text.  In fact, a big part of my thought for OpenHAB general user base was how easy it is to set up and get working, giving very good security for very little effort (an excellent tradeoff, as opposed to the aforementioned headache-inducing wall of text further down on that same page).

And that is before even getting into the fact that the entire certificate signing infrastructure is almost certainly backdoored by a host of various 3 letter agencies, and yet a quite detailed instructions on how to implement your own SSL solution still takes up the vast majority of the page.  I'm sorry but I just fail to see how recommending Wireguard is any worse than *that* in terms of a specific security recommendation.

All due respect @rkoshak, it appears to me you are perhaps not so familiar with Wireguard.  Which is understandable if you have a solution you have been using for long time and are happy with and works for you.

For me, I decided to finally implement something much more recently (within last few years), and I did my research within that time period based on current state of the art and therefore I think I therefore reached a very different conclusion.

Anyway, Rich, I know you are a tech guy in general clearly as we seem to have a lot of the same interests (home automation, etc.).  Maybe give it another look when you have some time, it's a fascinating bit of kit!

If the decision is in the end to make a sort of short list, I guess getting Wireguard into the list is better than nothing, as any astute person doing their own research should in pretty short order be able to see the benefits of it.  I think Wireguard is slowly but steadily starting to gain recognition in general, I am just trying to help speed that process along as I truly do think it is a better option (and at any rate certainly better than some of the current options / recommendations).

Cheers!  :beers:

**Comment by TRSx80** [comment]
> write a tutorial on the forum

OK, fine!  I officially added it to my `todo.org` list.  No promises as to time frame, however.  :wink: 

To be clear, this is "in addition" to hopefully being featured on some "short list" in official docs.

And happy father's day to any of you who are!  My family is mostly leaving me alone today in my lab as a "present."  :beers:

**Comment by rkoshak** [comment]
> However I would point out that lumping Wireguard in the same basket with all of these other traditional VPN solutions is a quite incorrect assumption, as Wireguard works very differently from the others.

And OpenVPN works very different from L2TP/IPSEC which works very differently from SSTP which works very different from PPTP. So Wireguard is different like everyone else. I don't see how that's an argument for or against it or why Wireguard is *special*.

> For example, it completely eschews AES encryption, making it ideal for the sort of embedded devices (without hardware AES support) that OpenHAB often is run on, making it a much faster throughput option in practice.

If security is actually something you care about, you should *not* be running your VPN server on the same machine as anything else sensitive. I and many others would consider openHAB to be sensitive.

> giving very good security for very little effort (an excellent tradeoff, as opposed to the aforementioned headache-inducing wall of text further down on that same page).

*Any* VPN solution is orthogonal to the so called "wall of text." It's an apples and oranges comparison. Not everyone can use a VPN. Some ISPs forbid it. Most work networks forbid it. Some countries have made running a personal VPN or even connecting to a VPN illegal (and we have users in those countries too). For those users who need to access their openHAB instance who:

- can't or don't want to use myopenhab.org
- can't or don't want to use a VPN
- can't or don't want to host their own instance of the openHAB Cloud Server

a reverse proxy is their only option. It will work anywhere in the world where the world wide web works.

> All due respect @rkoshak, it appears to me you are perhaps not so familiar with Wireguard. Which is understandable if you have a solution you have been using for long time and are happy with and works for you.

I've a MS in security engineering and do computer security engineering as a career. It's almost literally my job to be knowledgeable about this stuff and keep up with new capabilities and products. I've actually read the [protocol](https://www.wireguard.com/protocol/) specification and their initial [whitepaper](https://www.wireguard.com/papers/wireguard.pdf). I've installed and configured it and played with it. I've spoken with some of the foremost experts in cryptology about it. I've spoken with people who have tried to deploy it at scale (and the horror stories and problems they encountered). 

My position does not come from ignorance. It comes from a broad view of security over all (security never comes from deploying a point solution like Wireguard) and years of experience helping openHAB users on the forum which gives me a good feel for what is and is not always feasible for the broadest set of openHAB users.

It's clear you like Wireguard. I like it too. That doesn't mean it's the right solution for everyone. It's not even necessarily the right solution for most of openHAB users. Frankly, I shudder at the thought of most users punching a hole in their firewall for *any* reason. 

It doesn't make sense to take sides in this in the official docs. 

Frankly, if security is a concern for users my recommendations would be, in order:

- use myopenhab.org
- deploy your own instance of the openHAB Cloud Service on a VPS
- deploy a personal VPN service (of your choice) on a VPS; Algo is a script that will do this automatically for you with Wireguard
- deploy a VPN service like Hamachi which allows remote access to machines

Note the one thing that all of those have in common. None of them require punching a hole in your firewall. Anything that requires punching a hole in your firewall, be it running a VPN, ssh tunnel, or reverse proxy is not something you should be doing unless you also have the time and willingness to monitor the heck out it because it will be under constant attack.

**Comment by mstormi** [comment]
FWIW, openHABian now has an option to install WireGuard
(and the Tailscale option)

Regarding this issue, I'd think it's out of scope for openHAB (a _smart home control software_) to recommend or dictate anything like a specific VPN solution.
And given there's no more responses in half a year @Confectrician I suggest you close this.

**Comment by TRSx80** [comment]
> Regarding this issue, I'd think it's out of scope for openHAB (a _smart home control software_) to recommend or dictate anything like a specific VPN solution.
> And given there's no more responses in half a year @Confectrician I suggest you close this.

As OP, that would suit me just fine, for whatever that's worth.  Conversation seems to have run it's course anyway, with several people making their opinions well known.

**Comment by Confectrician** [comment]
I would still vote for a security overview which is taking care of several aspects.
But it would need one to write this.

Therefore i a would agree to close this for now.
Maybe someone will catch this problem up at some time.
