### ISSUE TITLE
http://openhabianpi:8080 redirects to a malware site

### ISSUE THREAD

**Issue by bensinc** [openhab/openhab-docs#1272]
Many places in the documentation tell the user to visit http://openhabianpi:8080 to begin setup, but if you try to visit that before it's available, or have some other DNS issue, many browsers will try to visit http://openhabianpi.com instead, which distributes malware.

Unless someone can contact whoever hosts that site and get it shutdown, I would change the documentation to have the user find the IP address and go there. Other places in the documentation use that method instead of trying to resolve http://openhabianpi:8080.

**Comment by mstormi** [comment]
please change the docs wherever you see this from "openhabianpi" to "openhab".
I have just seen it once (on the Android page) and changed it there so I don't know what those "many places" are you refer to.

FWIW, I also contacted their DNS provider

**Comment by mueller-ma** [comment]
Thanks for bringing this up. I merged the PR by @mstormi, so the url is going to be vanished from the Android docs page soon.

**Comment by mstormi** [comment]
FWIW I had contacted the domain provider but it was a thick-skinned ignorant guy that kept responding it wouldn't be any of his business. So no luck in getting that domain down.

BTW we have changed (back) to "openhabian" as a default hostname lately. I think docs reflect this but please help with cross-checking.

**Comment by Confectrician** [comment]
Thanks for the information.
Since we are then affected by the docs too, i will reopen.

You may want to have a look at:
https://github.com/openhab/openhab-docs/actions/runs/483499849

I have added automatic link checking for the docs today.
(Currently disabled, because i have to do some custom config for our internal links.)

We may also want to prevent users from getting redirected over there.
@ghys do you think we could do some link magic for that malware domain like we are doing it for the community link?
Technically this should be the same.
We could redirect everything from openhabian[dot]com to the docs main page.

**Comment by ghys** [comment]
Uh? No we can do redirects on openhab.org only. Or I didn't understand.
You can remove the automatic linking by e.g. transforming these URLs into inline code with backquotes, they shouldn't be made clickable.

**Comment by Confectrician** [comment]
Nevermind you are right. I had the redirects in mind from the wrong direction.

If we transform openhabian to inline code we should be consequent and do that with openhab/localhost and other urls used in examples too.

**Comment by Confectrician** [comment]
So before leaving this open for the next weeks again, i did a quick lookup and changed all relevant url parts in #1450.
There was just one occurence of `openhab` which i changed to `openhabian`.
