### ISSUE TITLE
Openhab2 - Cannot link my amazon account

### ISSUE THREAD

**Issue by Gewuerznud3l** [openhab/openhab-docs#1279]
Hello guys, this is my first issue here... excuse me if I do anything wrong.
I started setting up openhab today. I have the webserver running on a raspberry pi 4 and now I want to control my devices with alexa. I installed the Amazon Echo Control Binding and went to /rpi4:8080/amazonechocontrol/{my id}. (rpi4 is my pi's hostname) I landed on the sign-in page of amazon alexa, signed in and was sent to a page to approve the login. Therefor Amazon sent me an Email with a link to approve the login, wich I did, but before finishing, the site of my pi got reloaded and showed the alexa sign-in screen again. This keeps looping. I tried to approve really quickly (the site is reloading after about 10 seconds) and succeded, but it didn't work. 
Please help me. Thanks a lot!

<img width="640" alt="sign-in" src="https://user-images.githubusercontent.com/73387417/97080052-e439d480-15f8-11eb-9476-6601ec43c716.PNG">

<img width="640" alt="fail" src="https://user-images.githubusercontent.com/73387417/97080049-e3a13e00-15f8-11eb-8c99-18a96b64484f.PNG">

**Comment by GumbyMan82** [comment]
@Gewuerznud3l  I think the issue is in the wrong repository.
If you have an issue with the amazonechobinding, please report it in the openhab-addons repo.
I'm not quite sure if that can be done by the admins here...
So in order to speed things up, create a new issue and link the issue to this one here so that everybody knows that this can be deleted.

Onn the other hand, maybe it would help asking in the forum - i believe that somebody has faced similar issues and also found a solution.

**Comment by Confectrician** [comment]
@GumbyMan82 is right.

We can't help here on the docs side.
Please open a question in our forum https://community.openhab.org/
