### ISSUE TITLE
DiscoveryService example is causing warning

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-docs#1451]
When trying to implement the discovery as a ThingHandlerService (See this preview documentation: https://deploy-preview-1262--openhab-docs-preview.netlify.app/docs/developer/bindings/#discovery-that-is-bound-to-a-thing)
I get a error/warning:
Redundant superinterface DiscoveryService for the type PlugwiseHADiscoveryService, already defined by AbstractDiscoveryService

J-N-K suggested that it is a documentation thing :-) Originally posted here:
https://github.com/openhab/openhab-addons/issues/9742

**Comment by Confectrician** [comment]
Hey @lsiepel 

I reopened the original issue, since i am not able to write valid development docs currently.
Someone from the maintainers has to help out with it.

Anyways i would recommend to not use any preview page of the docs at all.
Those are meant for checking pull request changes and may contain work in progress data or (even worse) wrong information,
since those previews contain non reviewed content usually.

The article you are looking for, is currently only available in the `2.5.x` version of the docs.
If it is valid for openHAB 3 too i will add it into the latest docs too and someone with knowledge can improve it.
