### ISSUE TITLE
[WIP] Contribute to the documentaion FAQ

### ISSUE THREAD

**Issue by MyRaceData** [openhab/openhab-docs#1520]
This is to gather input on a document for frequently asked questions (FAQ) about contributing to the documentation for OpenHAB. Please feel free to add any potential questions which you believe should be included in this document.

First, @Confectrician is there a version of this document already existing which I can make pull request on? Or an issue already open or anything on the community forum? I searched both but could have missed something.

Secondly, if not (above question) should I start from a whole new document, copy an existing one or is there a template or something to start from?

I plan to post a thread on the community forum once I have a working version to get input. Please spend as little time on answering my two above questions as possible, I'm here to help you not bog you down. The questions below are simply possible questions to put in the FAQ doc. I do not expect them to be answered, I will research, document and write the answers myself.

Start with simple explanation of where the docs are stored, how to make a pull request ect.
how much explanation of how git works is needed?

Possible questions to include: (anyone please feel free to suggest questions to include) just a possible question is fine, I will find the answers myself to include in the doc. Thanks

How do I raise an issue on github

How do I create a PR on github

How do I find the right repository

What do I need to contribute

Where do I find documentation of markup language.

What markup language are the docs written in

**Comment by rkoshak** [comment]
Some relevant threads on the forum that already talks about a lot of this:

- https://community.openhab.org/t/wiki-how-to-contribute-to-the-openhab-documentation/111308
- https://community.openhab.org/t/how-to-file-an-issue/68464

> https://community.openhab.org/t/how-to-file-an-issue/68464
See the second link

> How do I create a PR on github
See the second link

> How do I find the right repository
It depends on what the issue/PR is to address. See the top part for the first link which explains where the various parts of the docs come from. But the most straight forward way with an existing page in the docs is to click on the link at the bottom of the page.

> What do I need to contribute
Time, a little knowledge, and a GitHub account. 

If you plan on making bigger changes, git installed on your machine and a good markdown editor/extension and maybe a git extension.

> Where do I find documentation of markup language.
> What markup language are the docs written in

Search the web for "Markdown Reference". There are a few special blocks that get processed by the compiler that converts the markdown to HTML but for the most part it's all Markdown. Probably the best thing to do with those sorts of things is to copy them from an existing page since they will need to match that anyway. Only someone adding a wholly new page would need to deal with them anyway.

Similarly, look at examples in the other pages for how to create the links to other pages in the docs. 

The last two questions should probably be merged into one.

Beyond that list I'd make sure to include:

- How do I sign off on a commit? Almost everyone who makes a first contribution runs into this when the DCO check fails.

I can't think of a whole lot more than that.

**Comment by Confectrician** [comment]
Thanks for starting this @MyRaceData and also thanks to @rkoshak for the good entrypoint.
I have also created a [DCO/Signoff Help](https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330?u=confectrician) some time ago, where you can find some info on signing off.

The first thread https://community.openhab.org/t/wiki-how-to-contribute-to-the-openhab-documentation/111308 is meant ot be served as a wiki at some point.
I could already make those posts wiki-posts, so thy can be edited by anyone interested. (Some of them are wiki posts already.)

I think the first posting is already in a good shape and explains "the documentation" really well.
(And i hope that the graphics are a bit catchy and help making this topic not get too long, even if it is much info.)

What would be pretty cool for one of the next small steps_
- Produce some basic explanations for the two contribution methods (small changes via web, bigger changes via vscode) we are aiming for in Post 2 and 3
- Make some proper screenshots/gifs showing the basic tasks in action

I have written down some basic vscode todo in a PR some time ago and will see if i can find it and link it here.

**Comment by MyRaceData** [comment]
Thanks Rich and thanks Jerome
by the way... this user Andrew_Rowe on OpenHAB community forum
Checking out the links, thanks a bunch guys for the head start, will get on Jerome's next steps first:

What would be pretty cool for one of the next small steps_

    Produce some basic explanations for the two contribution methods (small changes via web, bigger changes via vscode) we are aiming for in Post 2 and 3
    Make some proper screenshots/gifs showing the basic tasks in action

I have written down some basic vscode todo in a PR some time ago and will see if i can find it and link it here.

when you get a second or I'll search it out

**Comment by Confectrician** [comment]
Sorry for the delay.
I have searched but just found this PR with som esmall explanations and screenshots:
https://github.com/openhab/openhab-docs/pull/1420

I thought that had mad another one.

But the key facts are pretty quickly written down for vscode.

We should explain:

- How to fork a repository (Make the USer-Copy)
- How to clone this user repository locally and open it in vscode
- How to add a new branch for a contribution
- How to add changes to git and make a commit
- How to upload the commit into the users repos
- Reference then to the Pull Request explanation

When a pull request got merged there si one importiant thing we should explain too:

- How to keep a fork up to date
- Add a remote to the local vscode clone
- Get the latest "main branch" status from the openhab/openhab-docs repository
- Upload latest main changes into the user/openhab-docs fork

The latter points could go into a new post maybe.

**Comment by MyRaceData** [comment]
OK, Thanks for finding the PR, looks like some good info. I have to work my way thru the steps and document as I go. No worries about delays, we all have a life
