### ISSUE TITLE
Missing images on jsscripting addon docs pages

### ISSUE THREAD

**Issue by Redsandro** [openhab/openhab-docs#1714]
Some pages have missing images. I've noticed it before, but thought it was temporary.

https://openhab.github.io/openhab-js/
https://www.openhab.org/addons/automation/jsscripting/

![image](https://user-images.githubusercontent.com/1702193/147313691-791534d2-7674-43f3-8711-a7c308da7886.png)

The images show correctly [on github](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.automation.jsscripting/README.md) so I'm not sure at what point the docs publish script breaks the links.

**Comment by Confectrician** [comment]
Hey @Redsandro 

Thanks for your report.

> The images show correctly on github so I'm not sure at what point the docs publish script breaks the links.

The files from the addon repository on github get fetched fregurlarly into this repository, to prepare it for the "next" website build.
(Next is the homepage domain for our "latest" docs.)

![image](https://user-images.githubusercontent.com/7161177/147334558-9130cb58-754d-474f-a9d1-683eb2088705.png)

You can see that the latest "working" version is already correct here too:
https://github.com/openhab/openhab-docs/tree/final/_addons_automation/jsscripting

This page will get into the https://next.openhab.org build when it runs next time.
I will trigger that manually now to test it.
Probably the homepage simply was not updated yet.

But we have to ract for the stable 3.2.0 docs and edit this manually.
Those contents are not getting any automated updates after the release.
I will prepare a PR for this.

**Comment by Confectrician** [comment]
@digitaldan 

FYI =?> I can validate that the jsscripting docs make the `next` build fail.
I wil lhave to look into this.
Would be neat of you could leave out any docs updates to the addons repository until this has been solved.

**Comment by digitaldan** [comment]
I was using `docs` instead of the correct location , `doc` for readme images in  3.2 .  I did notice our official docs had the images missing and thought maybe this was a reason.  In any case it came up in the original code review, so i thought i should fix it along with some other small bits, which i did right after we released (so the current main branch should be correct) 

Has this been synced yet?

**Comment by Confectrician** [comment]
Yes it is synced into this repo already and is breaking the build currently.
I will have a look next days and probably we have to adapt the ruby script in the website repo again to make the build working.

It is a bit difficult to keep this functional when you have to look at several repositories.
Do you have any clue why we have a `doc` folder instead of a `docs` folder on the addons repo? (cc @kaikreuzer for opinion here too)

Github pages uses `docs` from what i know and several of the external repositories we have do so too. (Like alexa or google-assistant).
Would be nice if we could get this solved globally on long term and if the addons folder has no good reason for the structure it would be neat to have it adapted over there to match the common naming.

**Comment by Confectrician** [comment]
We should hava fix for the website build now, which means we can proceed here, when the preview build passes.

**Comment by Confectrician** [comment]
CHecked the latest build and both versions have the images displayed now.

**Comment by Redsandro** [comment]
> CHecked the latest build and both versions have the images displayed now.


@Confectrician the online version will be reflected later?

![image](https://user-images.githubusercontent.com/1702193/147586122-62ccb999-595c-41ed-be0f-e9daa52b69ac.png)

**Comment by Confectrician** [comment]
No. This is a page that is not maintained here.
It is completely maintained by the openhab-js maintainers. => cc @digitaldan
