### ISSUE TITLE
What means “combining” in Multi Binding / Channel Linkage? 

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-docs#1813]
https://www.openhab.org/docs/configuration/items.html#multi-binding-channel-linkage says:
> Commands and Updates from and to these Items will be combined, and can be used in interesting ways.

Please elaborate what means “interesting ways”?  What means “combining commands” and “combining updates”?

The application of Multi Binding / Channel Linkage is very sparely described.

**Comment by EnziinSystem** [comment]
I think OpenHAB took an unreasonable approach from the very beginning. The way object models are built should map 1-1 with reality. 
For example, we have a group of houses at the highest level, then a house with many floors, a garage, a garden... On a floor, there are many rooms, and each room has many devices.
Users should simply add or remove devices instead of struggling with vague concepts like Things, Binding, Channel, and Items. Very complicated and confusing.
However, the OpenHAB development team is very talented and has made a great contribution to the field.

**Comment by florian-h05** [comment]
> Users should simply add or remove devices instead of struggling with vague concepts like Things, Binding, Channel, and Items. Very complicated and confusing.

I have to contradict here. As openHAB is able to integrate a wide-range of devices which communicate over a wide-range of different protocols, there is some abstraction needed. I don‘t want to say that this abstraction couldn‘t be better in some other ways, but you need any type of abstraction. 
For example, when you have a look at HomeKit from Apple: There you can just add devices to the Home app on your iPhone and you are done, but those devices all have to speak the HomeKit Accessory Protocol.

Back to openHAB, where you have the following:
- Bindings: Those allow openHAB to communicate with devices using a special protocol. You can maybe think of the bindings as translator between the core of openHAB and your devices of that protocol.
- Things: Those represent a single device or bridge that is connected to openHAB using the respective binding. You can think of them like the one person that is speaking a universal language, that is speaking with the other person over the translator because the other person is speaking a special language.
- Channels: Things have channels. These represent the functionalities of your device (which is a Thing, it is connected with the help of a binding). You can think of the channels as questions or commands your person can tell the translator who translates them and tells them the other person. The other person responds, the translator translates and your person answers your question or gives feedback on your command.
- Items: Items are the thing on the top-level. They are linked to one or multiple channels and can get state updates or send commands to these channels. You can maybe think of them as something that remembers the answer to your question, or that takes your commands and tells your person that command.

I hope that helps a little bit.

**Comment by florian-h05** [comment]
@dilyanpalauzov 

> Please elaborate what means “interesting ways”? What means “combining commands” and “combining updates”?
The application of Multi Binding / Channel Linkage is very sparely described.

One example from my setup: I have a KNX installation and some of my KNX devices require the current time. openHAB can get me that time using the Network Time Protocol (NTP) Binding.
So, instead of setting up two Items and a rule to send the current time on update to the KNX Bus, I can simply link both my KNX channel for the time and the time channel from the NTP binding to a single Item:
```
DateTime        DateTime_de "Datum und Uhrzeit [%1$tA, %1$td.%1$tm.%1$tY %1$tH:%1$tM]" <time> {channel="ntp:ntp:germany:dateTime", 
    channel="knx:device:bridge:Wetterstation:Date" [profile="follow"], 
    channel="knx:device:bridge:Wetterstation:Time" [profile="follow"]}
```
The first channel link updates the Item with the current date and time from the NTP Binding, the second one is following the updates from the NTP Binding (with the follow profile) and sending the Date part to KNX, the third one is again following the updates from the NTP Binding (with the follow profile) and is sending the Time part to KNX.

**Comment by dilyanpalauzov** [comment]
So the first channel above is input-only (for time data), and the other channels are the output?

My reading of the documentation is that there are unlimited possibilities, like having an item with two input channels and one output channel.  How do both input-only channels behave in this case?

**Comment by florian-h05** [comment]
For my example, correct, the first channel behaves like an input channel and the two channels behave like output channels because of the profile `follow`.
But you can neither generalise this nor is this technically correct.
Technically, you don't have input and output channels, instead you define a channels behaviour with so called profiles, see https://www.openhab.org/docs/configuration/items.html#profiles.

The documentation says there are unlimited possibilities of combining channels. Yes, there are to many possible options to think of.
In my opinion, those options really depend on the use case and are very specific, so I cannot say something general.

If you link two channels without a profile, both can update the state of the Item and both receive commands from the Item.
A channel without any profile updates the Item's state and receives command from that Item.

**Comment by dilyanpalauzov** [comment]
May I ask one thing, which I do not understand about Channel/Things/Items.  When does it make sense to connect an Item directly to a Channel, and when it makes sense to use Item—Thing—Channel for state channels.

**Comment by dilyanpalauzov** [comment]
I mean for read-only data.

**Comment by rkoshak** [comment]
> May I ask one thing, which I do not understand about Channel/Things/Items. When does it make sense to connect an Item directly to a Channel, and when it makes sense to use Item—Thing—Channel for state channels.

The question doesn't make sense because connecting an Item to a Channel *is* Item-Thing-Channel.

Providing a summary of the concepts section of the docs:

- Things represent a device
- Devices have one or more sensors (i.e. a piece of information they report) and one or more actuators (i.e. something the device can do in the real world, like turn on/off a light). Each sensor and actuator is represented on the Thing as a separate Channel.
- Items provide a layer of abstraction so that no matter what technology is involved, a Switch is a Switch and it works the same way inside of openHAB. Items are Linked to Channels.
- Almost everything else in openHAB operates on Items, not Things and Channels.

An Item that is Linked is *always* connected directly to a Channel. Channels never exist independently of a Thing.

The original question here is what does it mean to Link multiple Channels to the same Item. The answer is "it depends". There are too many variables to provide a simple answer. If one is a sensor Channel and the other an actuator, then the Item may update based on the sensor Channel but when you command it it will go out to the actuator Channel. (In truth both Channels will update the Item and both Channels with receive the command). It gets even more complicated when Profiles become involved.

Linking multiple Channels to an Item without a Profile is likely something that one will rarely encounter in practice. And where it makes sense to do so is going to be highly dependent on both what you are trying to achieve and the behaviors of the Channels involved in the linking in the first place.

**Comment by dilyanpalauzov** [comment]
> The question doesn't make sense because connecting an Item to a Channel is Item-Thing-Channel.

You are right.  I was not concentrated when I asked.

I think in my use case I do not need to link one Item to multiple channels.

I am closing this.  Nevertheless I think it would be useful to document some examples form multi-channel bindings, so that users can better imagine what the capabilities of openHAB are.
