### ISSUE TITLE
Document supported browsers

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-docs#2064]
Please write down which browsers and browsers versions are supported by Main UI, Basic UI, HAB Panel, CometVisu.

**Comment by florian-h05** [comment]
All modern browsers should be supported by the openHAB UIs. Creating and maintaing a compatibility list means that someone would have to test compatibility against various browsers, various versions on various platforms. 

I don’t see somebody volunteering for such a time consuming job, and I think I speak for the other UI maintainers as well when I say that my priorities are developing and improving the UI itself rather. 

In general, I’d not expect MainUI to run perfect on older browsers and devices like Internet Explorer in Windows XP or on Android 4.4 KitKat. For those devices, I’d rather try to use BasicUI. 

For MainUI, there is a definition of targeted browsers, which is used during the build process to provide polyfills for older targeted browsers that don’t support a used API, see https://github.com/openhab/openhab-webui/blob/3e1caad9cf07a668a8bf17afbbe50336f7569e1e/bundles/org.openhab.ui/web/package.json#L54.

**Comment by stefan-hoehn** [comment]
Here are my 2 cents:

For those who read along and are so technically-savvy, this is the list that Florian refers to:

"browserslist": [
    "Android >= 5",
    "IOS >= 9.3",
    "Edge >= 15",
    "Safari >= 9.1",
    "Chrome >= 49",
    "Firefox >= 31",
    "Samsung >= 5"
  ],

However, as mentioned by Florian, this doesn't mean that there has been anyone who tested the functionality against all of these browsers (which by the way isn't possible anyway due to the > sign) but only that the Javascript tries to achieve browser compatibility as good as possible. Testing browser compatibility in a serious fashion involves a huge effort.

I wonder, Dilyan, if you would step as a contributor and provide this information in the long run by writing frontend tests that cover a defined set of browsers automatically?

**Comment by dilyanpalauzov** [comment]
I asked, as it is unclear what can be used in the code and what not, e.g. CSS --variables.  Having (somewhere) a list of browsers clarifies what can be used.

I am not going to write test.
