### ISSUE TITLE
Incorporate OH1 docs and re-factor add-ons section

### ISSUE THREAD

**Issue by watou** [openhab/openhab-docs#280]
I am working on a PR to refactor the add-on pages to be generated and linked per source (esh, oh2, oh1) so name clashes don't happen and choices are clearer.  See also https://github.com/openhab/openhab1-addons/pull/5029

**Comment by watou** [comment]
Here are screenshots of the PR in progress.  

Individual bindings are removed from user-menu as there are too many.

Options to filter the flat list of all bindings to see only the kinds wanted.  Each checkbox explains the differences.

![bindings-p1](https://cloud.githubusercontent.com/assets/3008217/22502409/a1deb8c8-e864-11e6-8875-d4cb8fb5e68b.png)

The table of all bindings follows the above, but filtered based on the checkboxes.

![bindings-p2](https://cloud.githubusercontent.com/assets/3008217/22502413/a7b924e0-e864-11e6-98d2-ee406cc6328a.png)

Each binding generated and markdownified in a subdirectory by source of the binding `oh1`, `oh2` or `esh` (and others sources can be added later).  All the 1.x add-ons README.md files are now on `master` in openhab1-addons.  This document is located at `/addons/bindings/oh1/ecobee/readme.html`.

![addons-bindings-ecobee](https://cloud.githubusercontent.com/assets/3008217/22502618/933ee1e8-e865-11e6-80ae-6347e27d4e66.png)

**Comment by kaikreuzer** [comment]
Thanks @watou, looks nice!
A few comments, if you allow:
- I would remove the "eclipse smarthome" badge and only keep it as "openHAB 2.x". You might have noticed that I had changed the version of the Karaf features for ESH bindings to 2.0 as well, so they appear in the list all the same way. For the end user, it should not matter whether it is ESH or OH2 and I want to keep the path open to easily move bindings from OH2 to ESH without any visible impact to the user.
- The "install manual" category are actually the NOT supported bindings (as nobody tested them and as such are not part of the distro). I would therefore NOT list them here, since we only should list parts that ARE part of the distro. I would be fine with a separate page that lists them and asks users to test them and help adding them to the distro, though.
- For [this page](http://www.openhab.org/technologies.html) I started collecting logos and I planned to actually move them to the binding list - I think this would make it much more visually appealing. I don't have that ready yet, but you might want to consider this for the layout. The logo might possibly best go to where the badges are currently shown. Maybe we should also reduce the size of the badges (at least on the bindings, not on the filter options) to only "1.x", "2.x", "legacy".

**Comment by watou** [comment]
> I would remove the "eclipse smarthome" badge and only keep it as "openHAB 2.x".

Understood and done.  All ESH extensions will be treated as OH2 addons from the perspective of the documentation.

> I would therefore NOT list them here, since we only should list parts that ARE part of the distro. I would be fine with a separate page that lists them and asks users to test them and help adding them to the distro, though.

Could we compromise on this point, so that the "install manual" badge is unchecked by default, and the text describing its meaning is further improved?  IMHO it's much better to have a single index of all documentation per add-on type, so users can more easily help test the ones that are not yet included in the distro.  Otherwise, they (and their newly improved documentation 😄 ) are likely to be forgotten.

> logos

Logos will be gorgeous in the list.  Perhaps all square in a new column on the right edge?  It would get kind of busy if the title, badges and logo are all grouped on the left.

> badge size

The current badges are SVG files generated at https://shields.io/, but they don't offer a "single word" option.  I kind of like the current badges, but if you have suggestions for an alternative I will investigate.  Materialize has nothing suitable that I could find as an alternative to images.

**Comment by kaikreuzer** [comment]
> Could we compromise on this point, so that the "install manual" badge is unchecked by default, and the text describing its meaning is further improved?

We can! The new text looks pretty good, I think this is a good compromise.

> Perhaps all square in a new column on the right edge? It would get kind of busy if the title, badges and logo are all grouped on the left.

We can have a try - it might look awkward though on a single-column phone layout, if the logo comes last. Alternatively, we could also put a new column at the left side of the table. Let's simply experiment and see what looks nicer.

>  kind of like the current badges

Ok for me - if we leave them where they are, we have enough screen space.
