### ISSUE TITLE
Add-ons: missing configuration part

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#309]
@watou I just realized that with your big change to the Bindings section, this whole configuration part fell off the table:

https://github.com/openhab/openhab-docs/blob/44266484bf2abea81c0c1fc8738efbd79278eed6/addons/bindings.md#1x-bindings

**Comment by watou** [comment]
Most of it has been either restated more concisely and clearly at the top of the new bindings page, some of it was a valiant but now obsolete attempt to work around the chaotic state of the wiki where most pages had no guidance for OH2 users, and the incompatible bindings list was outdated, incorrect and better stated in the specific add-on's readme (which is true of Sagercaster and maybe a few others).  Happy to hear a different take!

**Comment by ThomDietrich** [comment]
Well I'm not sure if I'm missing something here. The following topics are not covered anymore:

* function and behave differently
* do not support the auto-discovery
* do not define openHAB 2 things and channels
* recommended to resort to native bindings if possible
* configured through text based files
* global openhab.cfg file. This file is not part of openHAB 2
* `<binding_name>.cfg`
* without the trailing "1"

On top of that, the whole paragraph was added [only 17 days ago](https://github.com/openhab/openhab-docs/blame/44266484bf2abea81c0c1fc8738efbd79278eed6/addons/bindings.md) by @sihui62 after countless forum questions how 1.x bindings are to be configured and used ([example from yesterday](https://community.openhab.org/t/install-ola-from-git-because-apt-get-does-not-work/21140/9)).

**Comment by watou** [comment]
> * function and behave differently
> * do not support the auto-discovery
> * do not define openHAB 2 things and channels
> * configured through text based files

Are we reading the same [page](http://docs.openhab.org/addons/bindings.html)?  My read of the new page is that these points are covered perfectly clearly, and a bit more accurately than the old page.

> * recommended to resort to native bindings if possible

"These newer bindings can be the easiest to use."  

I caution against editorialising further about which choices are better for the user, as we don't know their needs, and lots of people worked very hard over years on the 1.x add-ons, and they still have critical value for many openHAB users.  

Also, "resort" in this context is incorrect usage, as "resort" means a less preferred option due to some constraint.  For example, a user might resort to the legacy Exec 1.x binding if they can't make the Exec 2.0 binding work for them satisfactorily.

> * global openhab.cfg file. This file is not part of openHAB 2
> * <binding_name>.cfg
> * without the trailing "1"

Like I said, these were there because all of the linked wiki pages were mainly for OH1 users, with a few having information for both.  Chris and I fixed 189 1.x add-on documents to speak directly to OH2 users, so this stopgap configuration/migration information became moot.  If more information needs to be added to the Configuration or Migration sections of the site, then those would be issues to open against those sections. But all 1.x add-on documents new only refer to where their correct `services/<bindingID>.cfg` file configurations are to be added.

> On top of that, the whole paragraph was added only 17 days ago by @sihui62 after countless forum questions how 1.x bindings are to be configured and used (example from yesterday).

Yes, as the crisis for proper 1.x add-on documentation was mounting, which the proper inclusion of correct 1.x add-on docs resolved.   Regarding the example from yesterday, the user could have easily located the [correct information](http://docs.openhab.org/addons/bindings/dmx1/readme.html#binding-configuration) to answer his questions regarding configuration of the DMX binding.  

Should text be added for "install:legacy" and "install: manual" binding check boxes to encourage the user to check the box if they want to see those bindings listed?

**Comment by watou** [comment]
I think the issues described here are already addressed and that this issue can be closed.  @ThomDietrich, WDYT?

**Comment by sihui62** [comment]
> I think the issues described here are already addressed

Can't find the section anymore where the "trailing 1" info for installing a 1.x binding through addons.cfg is addressed, still questions in the forum:

https://community.openhab.org/t/is-the-mios-binding-auto-install-working-in-openhab2/22820/5?u=sihui

I don't think it is advisable to have the users edit all 1.x bindings wiki pages for that information.

**Comment by watou** [comment]
> Can't find the section anymore where the "trailing 1" info for installing a 1.x binding through addons.cfg is addressed

I think the important information that you rightly point out is missing needs to be under the [Configurarion/Services section](http://docs.openhab.org/configuration/services.html) or wherever it would be explained what belongs in addons.cfg.  Replacing that stub with something that explains how to configure openHAB would seem to be urgent! 😄 

> I don't think it is advisable to have the users edit all 1.x bindings wiki pages for that information.

The docs.openhab.org site should no longer refer to the old wiki for 1.x add-ons, and ideally should not link to the old wiki at all.  I absolutely agree that how to configure addons.cfg does not belong in each 1.x binding README.md file, but it also does not belong in the section that lists add-ons, since there is a whole section about how to configure openHAB.

**Comment by watou** [comment]
This issue should perhaps be renamed: "[Configuration/Services] Missing documentation"

**Comment by FRookie** [comment]
Do you know how to fix the problem ,please!!!:
 Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.ui.paperui 2.4.0.qualifier
[ERROR]   Missing requirement: org.openhab.ui.paperui 2.4.0.qualifier requires 'java.package; org.openhab.ui.dashboard 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab.core:org.openhab.ui.paperui:2.4.0-SNAPSHOT @ C:\openHab\1\git\openhab-core\bundles\org.openhab.ui.paperui\pom.xml: See log for details -> [Help 1]
