### ISSUE TITLE
Tutorial (Beginner) catch 22(?)

### ISSUE THREAD

**Issue by Idus** [openhab/openhab-docs#384]
Hello,

Yep, a true beginner here... trying to follow your tutorial for my new Raspberry Pi 3, model B

1. Downloaded preconfigured image openHABian (ver. 20170317)
2. Etcher:ed my SD
3. Inserted and booted RPi... waited loong time until need to login (openhabian/openhabian)
4. System told me it skipped(!) WiFi setup and no Ethernet cable - so stopped and need to be restarted???? No way to moving forward...

What the... But... It´s a RPi 3, model B - I bought it because it has built-in WiFi and no need of Ethernet.

After several restarts, I finally got a prompt and managed to write "sudo openhabian-config" where the system asked for a password (I wrote "openhabian") - but then was informed that no such command was valid!!!

I even dug up my Pine64+ (2Mb + WiFi-curcuit) and did the whole thing over with that one - with the exact same result!

Finally, I rewired my whole TV-setup in the livingroom to get that Ethernet connection that it wanted so bad. (I disconnected from my Media NUC to make sure it was working). BUT-I-GOT-THE-SAME-RESULT!

I sort of cannot move forward with installation because it cannot find the WiFi OR Ethernet - but I cannot manage to get the WiFi to work - since it just stops and I cannot find or get the tools that says how you set it up to work. *sigh*

So, I´ve now worked with both my RPi and Pine64 off-and-on during four evenings - but to no avail... I cannot install your software enough to even get to the point to see a GUI or even thinking of a smart home - with tutorials or not...

Getting frustrating!

So, either instruct my n00b rear to the phrase or tutorial details that I obviously have missed - or you need to make a real beginners tutorial - especially on how to get openHABian up and running on the latest hardware... or maybe it´s in how the openHABian installs itself that is messing it up? I wouldn´t know.

Right now I am truly frustrated in buying all this hardware and not even getting to first base... as in installing the OS that is. ;)

Help openHABian - you´re my only help!

Cheers,

/"Idus"

**Comment by ThomDietrich** [comment]
Hello Idus,
The documentation article at http://docs.openhab.org/installation/openhabian.html already tries to clarify most of the problems you are describing. One of these can be found in the "Raspberry Pi" section:

> Insert the SD card into the Raspberry Pi, connect Ethernet and power

Ethernet should always work. If it didn't for you, something pretty was pretty weird. Wifi is not mentioned there... Wifi is a slightly more complicated topic because you need to supply an SSID and password to continue, right? This is also part of the latest openHABian version **but** not documented yet because I wanted power users to thoroughly test it. I should write this documentation part soon and thank you for the reminder.

One more thing you should have done is check the openHAB forum [thread on openHABian](https://community.openhab.org/t/openhabian-hassle-free-openhab-setup/13379), just as the documentation article suggests. There you'll find news on all relevant changes, improvements, updates etc. If you wanted to use wifi, a simple search in this thread would have been enough. All changes can also be found in the GitHub releases page you've downloaded the image from. The instructions on Wifi setup can be found at either:
* https://community.openhab.org/t/openhabian-hassle-free-openhab-setup/13379/837
* https://github.com/openhab/openhabian/releases

From the back and forth you describe I get the feeling that you should take a step back and just follow the installation instructions step by step.

1. Download openhabianpi-raspbian-20170318-git9767b24-crc9616e8a1.img.xz
2. Write the image to your SD card (e.g. with Etcher)
3. You'll find the file openhabian.conf on the sd card, open it in a text editor
4. Uncomment and fill in `wifi_ssid=` and `wifi_psk=` 
5. Insert the SD card into the Raspberry Pi, connect Ethernet and power
6. (optional) Give the system 1-2 minutes to initialize, then you can connect via ssh (either with name `openhabianpi` or the IP you retrieved from your DHCP server / your router) - You'll see the setup log being filled.
7. Wait approximately 15-30 minutes for openHABian to do its magic, it's finished when: [look here](http://docs.openhab.org/installation/openhabian.html#faq-successful)

Let me know how it went.

**Comment by Sp4rtan** [comment]
I would like to join this conversation as I have a similar problem.
I tried to get things up with both the Pi3 and the Pi0w.
I followed the instructions strictly as mentioned obove.

As I have a pi0w wifi is my only choice.
After trying both of my wifi SSIDs I still cant establish any connection.

I dont know what else I could try... :/

**Comment by ThomDietrich** [comment]
Are you working with a RPi3, RPi0W or Pine A64? The article seems correct, no clue why this wouldn't work.

Please come to https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379 for more discussion of the issue.
