### ISSUE TITLE
Write a REST API documentation article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#490]
http://docs.openhab.org/configuration/restdocs.html

The REST API with the provided web interface is probably one of the most underrated components of openHAB. An article, maybe under "Advanced Functionality", should describe the value of the REST API and showcase the possibilities.

* Retrieve data from an external application
* Inject data from an external application
* Inspect a Binding/Thing/Item, learn about current states, thing parameters or problems 

The last point would probably be interesting to many but known to none. Inspecting an Item or Thing during setup/rule development is important and can be done by self-defined Items, via the Remote Console or through the REST API. Especially with the REST web interface, this is quite easy.

This issue is free to choose. The API is actually pretty self-explanatory and the article shouldn't create many issues. @bgilmer77 @LightIsLife

@kubawolanin you had recent contact with the API for the vscode extension. Anything you want to add?

**Comment by kubawolanin** [comment]
Great idea!
IMO the simplest way to explore the REST API is by visiting the following URL:
http://demo.openhab.org/doc/index.html

Expanding each section will reveal the corresponding API endpoints along with the HTTP method to achieve what you need.

[Swagger](https://swagger.io/) is a great tool for exploring and designing APIs. Maybe it has a feature that generates a Markdown documentation as well?

@ghys has been working with the API as well lately. Let [this post](https://community.openhab.org/t/flows-builder-a-visual-designer-for-the-new-rules-engine/33443/16?u=kubawolanin) be an example of how powerful this API can be, combined with a great idea and execution 😮

**Comment by ThomDietrich** [comment]
Hey Kuba! The URL you've posted is what I was referring to as "REST API web interface". Of course every user has the same interface in his local installation as well.

> generates a Markdown documentation

Do you think something like this would be needed? After all the mentioned URL already does present the available options. A separate per-element documentation is imho not needed. It would be more important to describe what these REST, API and CRUD thingies are and why a user would want to bother looking into them. Wdyt?

**Comment by ThomDietrich** [comment]
@LightIsLife it seems like you are looking for an interesting issue to work on... Great :D Would you like to work on this one? It sure is important and so far a clean slate. An alternative would be to continue on one of the Transformation articles.

**Comment by LightIsLife** [comment]
@ThomDietrich thanks much for the pointer, indeed I was looking for issues that have no one working on it yet. Happy to take a stab, progress will be a little slower, as I have little practical experience with REST API yet.

**Comment by LightIsLife** [comment]
@kubawolanin @ThomDietrich I started to look into this and it appears that swagger is already integrated and actually is the tool that makes the nice presentation of the REST API in OH2 (when REST documentation is installed); not sure what to add there. 
I developed some text that is designed to help people understand why they should care about the REST API to begin with, but not quite sure where to go from here, if it is necessary at all to go any further. 
Happy to add a few examples, but, unless I get it wrong, the REST API truly lives up to its potential when OH2 is integrated into other applications. This is a harder sell for those who do not intent to do that, as likely applies to most beginners and programmers know what they need to do anyway already. 
In any case, here is the draft I have, let me know if you think it matches what you had in mind and I start working on a PR:
-------start draft------------
REST API

The REST API provides access to all the relevant information of a running openHAB installation. Examples of this information include all information on items and their State, installed bindings, sitemap info, and much more. The information exchange takes place through HTTP and is bidirectional, information can be sent and received by openHAB. 

REST API stands for **Re**presentational **S**tate **T**ransfer **A**pplication **P**rogramming **I**nterface. In short REST API allows other programs to access openHAB in very nuanced ways either to invoke changes to openHAB or to retrieve specific information. REST API provides a standardized platform for information exchange among different computer systems. 

The REST API provides only an interface to openHAB that can be used programmatically. However, from a technical perspective it is very easy to use. REST API is not automatically installed in openHAB. It is available in the PaperUI in the section addons under the tab MISC, it is listed there as REST documentation. The REST API can be accessed by connecting the browser to: http://123.456.789.000/8080/doc/index.html (with 123.456.789.000 being the ip address of the computer that runs openHAB. Access over the internet to the REST API is possible but users are encouraged to ensure safe and secure connections. This can be achieved by using [myopenHAB cloud services](http://docs.openhab.org/installation/security.html#myopenhab-cloud-service) or a  [reverse proxy server](http://docs.openhab.org/installation/security.html#nginx-reverse-proxy)

Some tasks that can be accomplished by using the REST API:
- Using third party software on cell phones, such as tasker to [open your garage door](https://community.openhab.org/t/triggering-items-using-openhab-2s-rest-api-from-tasker/14027)
- Interacting with openHAB via other programs, several computer languages offer libraries to easily acces openHAB’s REST API
- Accessing of information from devices that support http communication
- Updating Item States through external devices that are capable to send http commands (for example, certain motion detectors or surveillance cameras)

One final remark, when openHAB’s REST API is accessed from another domain, the following error may be encountered: ```No 'Access-Control-Allow-Origin' header is present on the requested resource```. In this case, it has been [reported](https://community.openhab.org/t/cors-problem-at-rest-api/3712/10) to be necessary to add the line ```org.eclipse.smarthome.cors:enable=true``` into the file services/runtime.cfg. 
------------end draft--------------
Any and all comments are more than welcome, especially, if I missed where you wanted to go with it.

**Comment by ThomDietrich** [comment]
Excellent start @LightIsLife ! I think this pretty much goes into the right direction 🎉 

> swagger is already integrated

Yes, I think that was a misunderstanding of what was Kuba was trying to say.

> help people understand why they should care 

The main goal 👍 

> Happy to add a few examples, ... harder sell ... programmers know what they need to do

I think we should discuss this.
First, yes of course, a normal user might not need to know about the REST API. There is nothing to sell. Carrying on :blush:
The last part is where I'd reconsider. Just because someone is an advanced user or a programmer by education, doesn't mean that he/she/it knows what an http REST API is and how to use it.
Now we already have a great introduction and swagger offers all the API documentation. The only thing I would add to the docs document is one single example for basic actions like Reading and Updating an Item or Accessing the Thing status. A document with these parts would be a more than sufficient reference to post in a community thread, next time a user asks how to integrate their own special script with openHAB.

> -------start draft------------

First and second paragraph are great.

The third paragraph is (we had this topic earlier today) sidetracked. How to install the addon and how to access the webpage via myopenhab should imho not be part of the REST article. How about something like this? "After the REST API documentation add-on was installed, it is accessible through the openHAB dashboard". Voila 😄 

That's as far as my first micro-review goes. @kubawolanin any additions?

**Comment by bgilmer77** [comment]
👍 +1 to what Thom said. At the risk of making a suggestion I do not have time to do myself, a simple example integrating with Node-RED (really simple!) might help to show how it could be used. 

Very nice job from what I can see from n my phone.

**Comment by ThomDietrich** [comment]
Thanks @bgilmer77,

Regarding the Node-RED suggestion: Please do not mix documentation and Tutorials. There are quite a few tutorials about how to Integrate systems like Node-RED with openHAB. The documentation should stay neutral. My suggestion is to show basic commands (either as simple URL requests for GET or curl calls for POST) and their result/effect.

Integration with a specific tool is then indeed up to the user and can be discussed in the community for specific use cases.

@LightIsLife I can post a few example calls later when I'm home, if that would help!?

**Comment by LightIsLife** [comment]
@thomdietrich. Thanks much for your quick feedback. I take all the examples
I can get 😀

**Comment by bgilmer77** [comment]
@ThomDietrich I completely agree. The first thing I thought of before I finished reading all of your note was curl.

**Comment by ThomDietrich** [comment]
@LightIsLife actually examples from my side are not needed, the curl examples in swagger are enough. There is even a Windows binary for curl.

**Comment by bgilmer77** [comment]
@LightIsLife I took the liberty of providing some edits based on your excellent contribution.  Please feel free to accept or discard these inputs.  Since I did some major reformatting, I have just posted my redraft without any diff from the original.  Let me know if you would prefer me to run a diff and post that as well.

@ThomDietrich I included your language for the third paragraph as well, although the third paragraph has been merged and reworded anyway.

REST API

The [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API provides both the ability to access a wide range of information associated with a running openHAB installation, and the ability to invoke changes to the openHAB installation. The information available from the API includes Items and their State, installed bindings, sitemap information, and much more. The information exchange takes place through HTTP and the API provides a standardized platform for information exchange among different computer systems.
The REST API provides an interface that may only be accessed programmatically. However, from a technical perspective it is very easy to use. Be aware that the REST API is not automatically installed in openHAB. After the REST API documentation add-on is installed, it is accessible through the openHAB dashboard.  Access the REST API by connecting any browser to: http://123.456.789.000/8080/doc/index.html (with 123.456.789.000 being the ip address of the computer that runs openHAB). Access over the Internet to the REST API is possible but this represents a significant security risk, and users are encouraged to ensure safe and secure connections. Some ways this can be achieved include using [myopenHAB cloud services](http://docs.openhab.org/installation/security.html#myopenhab-cloud-service), a [reverse proxy server](http://docs.openhab.org/installation/security.html#nginx-reverse-proxy), or a VPN.

Some tasks that can be accomplished by using the REST API include:
- Using third party software on cell phones, such as tasker to [open your garage door](https://community.openhab.org/t/triggering-items-using-openhab-2s-rest-api-from-tasker/14027)
- Interacting with openHAB via other programs; several computer languages offer libraries to easily access REST APIs generally, including openHAB’s REST API
- Accessing of information from devices that support http communication
- Updating Item States through external devices that are capable of sending http commands (for example, certain motion detectors or surveillance cameras)

One final remark - when openHAB’s REST API is accessed from another domain, the following error may be encountered: No 'Access-Control-Allow-Origin' header is present on the requested resource. In this case, it may be necessary to add the line org.eclipse.smarthome.cors:enable=true in the file services/runtime.cfg.
------------end draft--------------

**Comment by bgilmer77** [comment]
@ThomDietrich I am going to try to post the note above as a PR.  Hopefully I will do it correctly.  If not, please advise.

**Comment by LightIsLife** [comment]
@bgilmer77 thanks for your edits; was planning to do the same (posting a PR), but go ahead....and thanks
@ThomDietrich thanks for your comments as always; I was wondering why we would not take the examples from the swagger, but as I have no experience in using the REST API myself, I thought your examples may go beyond what is provided there.

**Comment by bgilmer77** [comment]
@LightIsLife please make the PR. I am still learning about using GitHub. You should get the original attribution. I will contribute once I see the PR.

**Comment by LightIsLife** [comment]
@bgilmer77 I am no expert either ..... but will do, thanks

**Comment by bgilmer77** [comment]
@LightIsLife Please post one final time here when you have finished the PR.

**Comment by LightIsLife** [comment]
created PR #508

**Comment by bgilmer77** [comment]
@LightIsLife forgive me - I am still learning about the etiquette I should follow in this community.  Markus, I note that you posted your version without my update.  Is that because you disagree with my suggestions, or because you wanted to track the changes using your PR?  Please take a look at what I wrote above and let me know if you want me to suggest these changes on your recently posted PR.

**Comment by LightIsLife** [comment]
@bgilmer77 mmmhhhh....now I am confused; I am pretty certain that I copied your post (the one 8 posts up); I moved a sentence or two replaced a verb (provide) to avoid duplication, added the curl examples and some links; what did I miss? 
I certainly intended to start with your great edits and NOT my original post; apologies if I missed anything. 
And no worries about etiquette, ask as many questions to get the clarity you need. Just comment on the PR as much as you need. This doc contributions need to make sense to as many as possible, so if what is in PR508 does not make sense to you, comment away, I welcome it; and again very sorry if I messed up, I like your edits!!!

**Comment by bgilmer77** [comment]
@LightIsLife Okay, and thank you.  Let me comment on your PR and then you can see the differences.  That is the easiest way - and besides, I may have made a mistake and you copied everything I had.
