### ISSUE TITLE
Items: Add a chapter about the actual Item state

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#507]
The Item article currently discusses the Item syntax and usage. So far completely ignored is the question about the Item state, e.g. Initialization, UNDEF, Binding influence etc.

The chapter will probably be short.

Please collect ideas what needs to be mentioned here!

**Comment by bgilmer77** [comment]
Clearly we need to talk about the states themselves.  If anyone has a state diagram handy, then a short table of allowed states and their meaning would be helpful.

The section of the documentation on persistence and how to get Item states to persist across reboots is very clear, so obviously all we need are pointers to that information, but for someone who is just starting, they are likely to focus on Items before they look into persistence.  So it would be good to explain WHY certain Items will come up with correct states (updated by Bindings, for example), and WHY other items, a select function, for example, will come up in an UNDEF state.

Agree - chapter does not need to be long.  But it would be good to add enough here to give a general picture of what to expect if values are not initialized in rules, if persistence is not installed, etc.  Also, pointers to relevant information in the existing documentation could likely make up most of the chapter since the information about states etc. is in a number of places and does not (should not) be repeated.  (One source of the Truth - no?)
