### ISSUE TITLE
[Proposal] "Edit this page on GitHub" link

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-docs#530]
The goal of this proposal is to encourage more people to contribute to the documentation pages.

So let's say that user visits [this page](http://docs.openhab.org/developers/contributing/contributing).
Adding the following example code at the beginning of `.content` class:
```html
<a href="{{TODO}}" style="float: right">Edit this page on GitHub</a>
```

Would result in effect like this:
![przechwytywanie](https://user-images.githubusercontent.com/2270505/31588114-7053186e-b1ed-11e7-8527-f44f9a0a6cd8.PNG)

The URL would then redirect (or open a new tab if `target="_blank"` was used) to a GitHub article. In the example above it would be [this page](https://github.com/openhab/openhab-docs/blob/gh-pages/developers/contributing/contributing.md).

Resources:
* https://github.com/jekyll/jekyll-help/issues/5

**Comment by ThomDietrich** [comment]
Hey Kuba!
That's a good idea! I was also thinking about adding such a link. I wanted to go with a [Materialize floating action button](http://materializecss.com/buttons.html) for it.

The big problem is that the majority of content in docs is not actually hosted in the docs repo and the URL to the original file would need to be known. To that end I started to add the `source` font matter to files, see [here for an example](https://raw.githubusercontent.com/openhab/openhab-docs/gh-pages/_addons_bindings/astro1/readme.md). However (it would be possible) not all files can be provided with that field easily. That's why I've just recently discussed the idea of additional [metadata](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/ESH-INF/binding/binding.xml) for all addons with @kaikreuzer. We wanted to discuss this step at the Smart Home Day. You should join! 😉 

Best! Thomas

**Comment by kubawolanin** [comment]
> Let me know if you are interested in more details

Sure I am :)
And I really like the idea of incorporating floating button there.

Cheers,
Kuba

**Comment by bgilmer77** [comment]
Would the `source` front matter be applicable to other areas of the docs?  As you know, we have other places where an article may appear in openhab-docs, but it is actually an ESH article.  (Or is this a different concept?)

**Comment by ThomDietrich** [comment]
The exact same topic yes. I've started another discussion that hopefully will soon help with the this feature

**Comment by Confectrician** [comment]
> I've started another discussion that hopefully will soon help with the this feature

Could you link it here, if its a public visible discussion?
Would be nice to have an impression of the whole topic.

**Comment by ThomDietrich** [comment]
Sure, here you go: https://github.com/eclipse/smarthome/issues/4503

**Comment by kaikreuzer** [comment]
@ghys has added such links on the new website, so I guess this can be closed.
