### ISSUE TITLE
Create a set of super simple examples

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#586]
This has come up twice today on the forum. There is a big gap for new non-technical users to get started with OH. Many if not most of the examples in the documents are too complex, too late in the docs (i.e. users give up reading before they get to the examples).

I propose adding:

- a section in the beginner's tutorial to describe text based Item configs
- supplemental pages with examples, one for Items and one for Rules linked to from both the User's Guide and from the Beginner's Tutorial

I'm thinking of a progression of super simple examples like:

```
Switch UnboundItem // an Item without any config or link to a Channel or binding
Contact ItemWithIcon <window> // an Item with an icon but no other configuration
...
Number Temperature "My Temp [%.1f C]" <temperature> { mqtt=<[ blah blah blah] , expire="5m" } // Item with two 1.x binding configs
Switch Light "My Lamp" <light> { channe="zwave:dongle:node2:switch_binary" } // Item linked to a channel
```
```
// Start with the two rules already on the Beginer's Tutorial
rule "Handle Presence changing in a single rule"
when
    Item Presence_Mobile_John changed
then
    if(Presence_Mobile_John.state == ON) Wallplug_FF_LR_TV.sendCommand(ON)
    else Wallplug_FF_LR_TV.sendCommand(OFF)
end

rule "Trigger rule at a certain time"
...

rule "Use a timer to turn on the TV 5 minutes after coming home"
...
```

The intent is to show a set of rules that gradually increase in complexity and introduce some key OH and general programming concepts like defining context with { }.

A lot of non-technical users are having a lot of trouble making the leap from the Beginner's Tutorial to the Rules docs in the User's Guide and they believe (and I agree) simpler examples might help bridge that gap.

**Comment by Confectrician** [comment]
Hey @rkoshak,

Thanks for the proposal.

I think it is partly based on https://community.openhab.org/t/please-send-basic-rule-examples/37062/31 from my own readings this evening.

If you have other threads in mind, which made you file this issue, please mention them here too.
This way everyone can read all recent topic related content and get an overview of the needs.

**Comment by rkoshak** [comment]
There was another one and I can't find it anymore. That is what happens when you read every post. I'll give it another go. The root problem of the post was the OP didn't understand basic Items syntax even after reading (or claiming to have read) the Items Docs. Their claimed problem was they couldn't figure out how to reference an Item from Rules. The OP's picture looked like a Simpson's character. That is all I have to go on right now. :-(

**Comment by Confectrician** [comment]
No problem, we can add that later or add others when they are related.
Just wanted to get an overall overview, of the problems that confuse people.

**Comment by rkoshak** [comment]
Here is the one that you already know about.

https://community.openhab.org/t/wtf-rules-in-oh-2-1/37066

**Comment by bgilmer77** [comment]
+1 to this project.  We have to make it as easy as possible to go from zero to up and running for someone who has some basic computer knowledge, but zero exposure to OH.

This is a topic that is very near and dear to my heart.  If there is not an easy on-ramp for people who are interested in OH, they will ditch it in frustration after their initial attempts.

Speaking from my own experience, I started working seriously with OH about six months before OH2 came out.  The examples were helpful, as were the tutorials, but I also found myself searching for a lot of information before I finally got my head around how things work in the OH environment.

As an example, I think first-time users will try a LOT of different things initially, some of which will work, and some of which will not work.  So as an example where I was banging my head against the wall, I installed and removed Things and Items frequently initially during the transition to OH2.  I kept bumping up against strange behavior related to "ghost links" (don't know what else to call it) that were left over when I deleted an Item.  I had to search the forums to find the information about how to delete these using the console in order to get OH2 straightened out again.  And in fact, I had blown away and reinstalled OH2 about four times to get rid of the ghost links before I finally said, "there has to be another way".  As a system administrator, I am willing to stick with it and search forms and the web to find solutions.  But end users will never do that.

So it is a combination of simple tutorials or docs, but also including hints not only on the "happy path" where everything goes perfectly, but also on the "unhappy path" where things are screwed up and you need to fix them.  In this case, it is a perfectly reasonable expectation to think that if you delete an Item and a Thing in Paper UI, you are good to go.  That is NOT the case, at least it was not the last time I checked, and so the way to get rid of "ghost links" should be thoroughly documented and easy to find in the core documentation that we would expect a new user to read.  It does not have to be in the mainline docs, but a clear reference in the docs to how to fix this is absolutely required.

This is not so much a point about "ghost links" as it is a point about how to write on-boarding documentation so that it eases the new user's adoption of OH.

My two cents.

**Comment by rkoshak** [comment]
This issue is still relevant but it can be combined with a larger "fix/complete the Beginner's Tutorial" issue. The approach I highlight above for how to write the examples is a suggestion and not necessarily the best approach. The key need is to have some examples with descriptions to help the new users bridge that gap between no experience with Rules and the mostly complete Rule examples in the docs and forum.

**Comment by Confectrician** [comment]
@rkoshak do you think this still makes sense?
We had tons of changes in openHAB and the whole docs meanwhile.

WDYT?

**Comment by rkoshak** [comment]
Wow, I completely forgot about this one. yes, I'd say that enough had changed that we should just go ahead and close it and if any of these points crop up again we can open new ones.

**Comment by Confectrician** [comment]
Thanks for the fast response.

I am trying to get rid of some outdated stuff and let the repo reflect the actual needed to-do's and active issues again.
