### ISSUE TITLE
"Binding" introduced without any short description

### ISSUE THREAD

**Issue by digicos** [openhab/openhab-docs#604]
Hi,
 I am a newbie to Openhab, and while going through the documentation at [this page](https://docs.openhab.org/concepts/things.html) , binding is introduced in [Thing Status](https://docs.openhab.org/concepts/things.html#thing-status). I would request to place a small introduction to what "bindings" are, just before mentioning it or provide a link to the relevant section.

**Comment by bgilmer77** [comment]
Hi @digicos.  Thank you for pointing this out.  Let me take a look at this.

**Comment by bgilmer77** [comment]
@digicos Question - would a link to [this](https://docs.openhab.org/addons/bindings.html) be helpful when the word Binding is first used?  Do you think we need some text specifically to introduce bindings?  If so, maybe it belongs on [this](https://docs.openhab.org/concepts/index.html) page?

**Comment by digicos** [comment]
@bgilmer77 , a text (along with mention to link for further exploration ) would be helpful to understand what bindings are and set a context for further understanding. For me it was more confusing and not able to visualize what binding in physical / logical terms could mean. "Things" section has a better explanation..
I still have unclear thoughts about "bindings"..are "bindings" physical or logical associations between "things" -> "things"
"things -> "items", "links", "channels" ??

**Comment by bgilmer77** [comment]
@digicos, please take a look at [this](http://docs.openhab.org/configuration/items.html#binding) article in the configuration section on items.  Once a binding for a specific physical thing (small "t", not capital "T" as in "Thing" in openHAB) is associated with an Item, the Item knows how to communicate with that physical device.  You can think of the binding as a translator.  So inside the guts of openHAB, no matter what brand of physical light switch you have, OH uses the same logic and the same architecture during configuration, and in the User Interface in order to represent that switch.  When you use the UI to tell OH you want to turn on the switch, OH tells the Item that you want to turn on the switch.  The item "talks" to the "top" of the binding, saying, "turn on the switch".  It is the binding code that understands that command from OH, and then sends a short note over an IP messaging protocol, say 0x01, that is the actual command the physical switch needs in order to turn on.  OH does not know that one talks to the switch using a particular messaging protocol or using IP.  It does not know that the "ON" command is actually 0x01 hex.  This "translation" is all handled by the binding.
The benefit of this is that the main body of the OH code remains the same, whether you are talking to a switch that communicates using WiFi (a WEMO switch, for example), or through Z-WAVE, a mesh networking technology.  The binding handles all of these device-specific details.  In computer science this is called, "Separation of Concerns", and it is a successful pattern that has been used in many different applications.

**Comment by digicos** [comment]
@bgilmer77 this clarifies my doubts..Thanks! The below paragraph about "binding" would be helpful in the introduction section.

> Once a binding for a specific physical thing (small "t", not capital "T" as in "Thing" in openHAB) is associated with an Item, the Item knows how to communicate with that physical device. You can think of the binding as a translator. So inside the guts of openHAB, no matter what brand of physical light switch you have, OH uses the same logic and the same architecture during configuration, and in the User Interface in order to represent that switch.

**Comment by bgilmer77** [comment]
@digicos I am glad this helped.  I will work to get something in the documentation quickly about this.  And thank you for bringing this up.

I am very focused on improving the experience of new users so this comment is really helpful.  Question - what OS are you using and are you having any other problems getting started?

**Comment by digicos** [comment]
@bgilmer77 I am using OpenHabian on Raspberry Pi 3, which i finished installing 2 days back without any  hassles. Windows 10 & Ubuntu as my development platform. 
I'll keep posting in case I hit another mental block!..

> **Just to add to the kind of user I am** : 
I work on technologies ranging from embedded systems to making web apps, so I find the documentation kind of easy to follow

Thanks once again..appreciate your efforts!!.

**Comment by ThomDietrich** [comment]
Hey guys, Thanks @digicos for your participation.

Three comments from my side:

1. The concepts articles are copied over from another place (the eclipse smarhome project). While this technicality shouldn't hinder improvements, I'd suggest to address the reported error inside the article rather than by linking another part of the openHAB documentation.
2. @digicos this is not the solution for the specific issue but from a general standpoint, I think [this](http://docs.openhab.org/configuration/index.html) article gives a quick simple overview about openHAB proper nouns.
3. This whole issue could also be addressed by implementing #538

**Comment by bgilmer77** [comment]
@ThomDietrich I have a single sentence PR that I could introduce over on eclipse/smart-home to address this specific issue.

`**Bindings** are add-ons that provide a way to tie Items to physical devices, and to abstract the specific communications requirements of that device into a more generic openHAB world of Things, Items and Channels.`
While the article you reference does give a short description for a number of critical OH terms, we are still at a point today where people who just go to the introductory documentation and start reading trip over the term Binding because it appears out of nowhere without any introduction.  I am ready to drop the PR in ESH if that is appropriate.

**Comment by ThomDietrich** [comment]
Sounds good. How about "link" instead of "tie"?

**Comment by bgilmer77** [comment]
Sure - I agree with link.  I will go ahead and drop this PR when I get a chance.

**Comment by bgilmer77** [comment]
Sure - I agree with link.  I will go ahead and drop this PR when I get a chance.

**Comment by bgilmer77** [comment]
Created PR eclipse/smarthome/#4899

**Comment by Confectrician** [comment]
If you remove the last / it will be linked automatically. 😃 

eclipse/smarthome#4899

**Comment by digicos** [comment]
Hi,
 Thanks for addressing this issue, I went through the documentation once again [here](https://www.openhab.org/docs/concepts/#things-channels-bindings-items-and-links) and could very well understand the concepts. Now that I got involved more into setting up my own system, things are perfectly making sense.. 
Should I be closing this issue?

**Comment by Confectrician** [comment]
I can do that for you. 👍 
Change is merged and problem solved, so no need to keep it open.

Thanks for pinging us on this.
Always good to get rid of not needed issues, to keep a better overview. 😃
