### ISSUE TITLE
OH User Manual - BigAssFan Binding - SiteMap Example

### ISSUE THREAD

**Issue by lews0r** [openhab/openhab-docs#607]
Example shows:
Slider item=PorchFanLight**Speed** label="Light Brightness [%s %%]"

Should be:
Slider item=PorchFanLight**Level** label="Light Brightness [%s %%]"

**Comment by bgilmer77** [comment]
Hi @lews0r, thank you for noting this issue.
If you don't mind, please create the same issue in /openhab/openhab2-addons. The addon you refer to is in that repository.

FWIW, I have already created a PR, /openhab/openhab2-addons/#3404 to address

**Comment by lews0r** [comment]
Sorry - was just for the documentation, the binding works properly. Should I still re-create in /openhab/openhab2-addons?

**Comment by Confectrician** [comment]
The documentation for bindings is maintained in the add-ons repo and copied over to the docs from time to time.

This is done this way to only have one location where you need to change something for one binding.

Please have a look at our readme here. We have a section called "automatic generated parts" which describes how we do that.

About your question: 
I think you don't need to file an issue there since Brad already opened a PR for this.

**Comment by bgilmer77** [comment]
Closing this issue.  PR openhab/openhab2-addons/#3042 has addressed this and has been merged.
