### ISSUE TITLE
Docs Versioning: Add 2.2.0 stable and 2.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#619]
After the openHAB 2.2.0 release and last improvements and corrections to the documentation it is time to update the versioning function (#520)

**Comment by kaikreuzer** [comment]
I just noticed something that I didn't had a close enough look at before: I see that you have created 2.1.0, 2.2.0, 2.3.0 etc. versions.
As I briefly mentioned in https://github.com/openhab/openhab-docs/issues/520#issuecomment-339998197, I would actually rather suggest to only have docs for minor versions, i.e. 2.1, 2.2, etc.

Note that we have the addons download site also only for 2.x and if there is a patch release, it will replace the older patch level. We should imho do the same with the documentation as we otherwise might get into too many identical copies of the docs (assuming that patches only contain critical fixes and thus do not really have any impact on the documentation content).

**Comment by ThomDietrich** [comment]
Caught me in the last second. Good point. On it.

**Comment by ThomDietrich** [comment]
![grafik](https://user-images.githubusercontent.com/2870104/34652148-a13b0eee-f3da-11e7-87eb-2c49f31c633b.png)

So you would prefer v2.3-SNAPSHOT, v2.2, v2.1
?

**Comment by kaikreuzer** [comment]
How about even simpler 2.1, 2.2, latest (which is imho more common on documentation than the technical word SNAPSHOT).

**Comment by bgilmer77** [comment]
Strongly agree with LATEST.  This is well aligned with the Linux world.

**Comment by ThomDietrich** [comment]
Makes total sense to me, I'm on it.

**Comment by ThomDietrich** [comment]
One thing I'd rather not change now (takes more time then you might think) but would be something to remember for next time. You seem to agree on the proposal by Kai, my current solution consists of "latest version, v2.2, v2.1" - If we want to get rid of the "v/version" that would be fine with me.

**Comment by bgilmer77** [comment]
Fixing this next time is just fine with me - I do not see that this is superurgent.

**Comment by ThomDietrich** [comment]
It's done.

Please forgive me for not going the Pull Request path. This process involves three branches and 3000 files and complicated enough 🙇 
Please check if you can find any issues: https://docs.openhab.org/

**Comment by kaikreuzer** [comment]
Nice work, many thanks! 👍
