### ISSUE TITLE
iCloud binding Account Thing lacks config explanation

### ISSUE THREAD

**Issue by bdleedy** [openhab/openhab-docs#628]
`Thing device myiPhone8 "iPhone 8" @ "World" [deviceId="VIRG9FsrvXfE90ewVBA1H5swtwEQePdXVjHq3Si6pdJY2Cjro8QlreHYVGSUzuWV"]`

It is unclear what `@ "World"` signifies and where to obtain the `deviceId`

**Comment by Confectrician** [comment]
Hi @bdleedly,

Thanks for posting this issue.

As information for you and others willed to fix this:

Since this is binding releated content, it is maintained in the corresponding addons repo and has to be fixed there.
(I think it's the openhab2-addons repo in this case.)

We grab the binding readme files from time to time and update the docs automatically then.

I will look up the current file to edit and link it here.

**Comment by ThomDietrich** [comment]
Hey @bdleedy,
your first concern is easily answered by the Things configuration article: https://docs.openhab.org/configuration/things.html#defining-things-using-files It is not related to the iCloud binding and should imho not be discussed there. What do you think?

Regarding your second issue, I agree. The article only says:

> A device is identified by the device ID provided by Apple. 

To be clear: The given ID is the identifier the device identifies itself with through the iCloud API. I am not an iPhone user and can't tell you how to obtain it manually. Maybe you can find an App to retrieve it?

Please add your concerns here and mention @pgfeller while you are at it: https://github.com/openhab/openhab2-addons/issues
