### ISSUE TITLE
Sync the contributing guideline from openhab-distro

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-docs#648]
@mueller-ma 

> https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md#community-guidelines
> https://docs.openhab.org/developers/contributing/contributing#community-guidelines
> Those both files seem to be the same file. It seems to redundant to maintain both. Can it be pulled from openhab-distro, when the docs are built (like USAGE.md in openhab-android)?

Yes good idea ;) I'll look into this (at some point in the future)

**Comment by mueller-ma** [comment]
We could also add all guidlines and a list with all maintainers in one repo and just link to this repo.

**Comment by Confectrician** [comment]
I am perfectly fine with creating a PR instead of committing directly.

About repo specific information:
That's of course a valid point and we should think about how to handle that.
maybe generalize the guidelines as much as possible (which maybe already is the current state) and generate them individually?

My intention was just to prevent forgetting about important guideline changes and the idea can be improved of course.
