### ISSUE TITLE
Caldav: Google deprecated commonly used endpoint

### ISSUE THREAD

**Issue by thucke** [openhab/openhab-docs#668]
The current examples of the [Caldav Command Binding documentation](https://docs.openhab.org/addons/bindings/caldav-command1/readme.html#google-2-factor-authentication) for connection Google calendars are shoing URL examples like `https://www.google.com/calendar/dav/email@gmail.com/events`.
However the [CalDAV API Developer's Guide](https://developers.google.com/calendar/caldav/v2/guide) states that this endpoint is deprecated and no longer supported.

Hence the binding should be extended to support Googles OAuth 2.0 authentication.
There were already activities and also a functional solution (see https://github.com/querdenker2k/openhab/pull/2) that I personally used in OH 1.8.

**Comment by Confectrician** [comment]
Hi @thucke 

Thanks for pointing out this issue.
All of our Binding Documentation is maintained in the corresponding Add-on Repos beneath the Binding code.
We grab it from time to time and update all Binding docs in one run.

For CalDav the location would be:
https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.caldav-personal

## What does that mean now?

The issue you are pointing out has to be filed in the right place.
In your case this would be the openhab/openhab1-addons Repository.
https://github.com/openhab/openhab1-addons/issues

Especially it does make much more sense in the other repo, because the documentation is not the root problem in this case.

**Comment by Confectrician** [comment]
Sorry that close was by mistake. 😄

**Comment by thucke** [comment]
Thank you @Confectrician 
[Issue #5557 opened](https://github.com/openhab/openhab1-addons/issues/5557)
Should this one stay open for later update of the documentation?

**Comment by Confectrician** [comment]
> Should this one stay open for later update of the documentation?

I would say no.
The documentation readme file is in the openhab1 repository too, 
so we should better keep an eye on updating the information there while introducing a possible fix/improvement.

What do you think?

**Comment by thucke** [comment]
Surely - thank you again.
Take care ..
