### ISSUE TITLE
Correct notation of macOS

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#685]
The desktop os by Apple is called `macOS`. Prior to Sierra they called it `OS X <codename> 10.<number>`, but they changed it to `macOS <codename> 10.<number>` See https://de.wikipedia.org/wiki/MacOS#OS_X_El_Capitan_10.11

Can I simply run sed over all files and open a PR or shouldn't it be changed in docs version 2.1 and 2.2?

**Comment by Confectrician** [comment]
> Can I simply run sed over all files and open a PR or shouldn't it be changed in docs version 2.1 and 2.2?

Since we do not changy any specific version related content here it would be fine for me, but maybe @kaikreuzer coudl share his opinion too.

also i would like to ask @ghys if the versioned folder have any effect on the new page of if they are just stored somewhere else for now?
I don't know what the last status with versioned docs was.

**Comment by kaikreuzer** [comment]
I am not too fond of changing history - in some way, the 2.1 and 2.2 documentation is a released artefact and I thus would't really touch it anymore, if not important.

But if you really feel it should be done, I won't stop you ;-)

**Comment by mueller-ma** [comment]
I opened https://github.com/eclipse/smarthome/issues/5672 for the macOS Text to speech addon.

**Comment by ghys** [comment]
> also i would like to ask @ghys if the versioned folder have any effect on the new page of if they are just stored somewhere else for now?

The version dropdown on the website simply redirects to docs.openhab.org/v2.x. The website doesn't host previous versions, and I believe the plan was to keep using the same pattern - docs.openhab.org/v2.x - for those archives (the 2.3 archive could/should be made with VuePress).

> 2.1 and 2.2 documentation is a released artefact 

I also noticed they don't display cookie consent banner since they were generated before it was added. Is it an issue?

**Comment by kaikreuzer** [comment]
> I also noticed they don't display the cookie consent banner since they were generated before it was added. Is it an issue?

Might be worth to change this indeed.

**Comment by Confectrician** [comment]
Then it will be fixed in the next update of external content.
I don't know if the jenkins build already executes a website redeploy, but can't be that long until it gets grabbed the next time.

**Comment by Confectrician** [comment]
https://github.com/openhab/openhab-docs/commit/35a9a2276acb5d4da36df1a629c7e2b72a91bd69

Seems that this works already, but isn't connected to the website build yet.
But it's in the repo already. :)
