### ISSUE TITLE
Proposed REST API paragraph

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-docs#713]
## Change the default listening port (8080)

Edit the file /etc/default/openhab2 and restart openhab.

**Comment by Confectrician** [comment]
Hi @olemr,

Can you provide some context?
Which file should be improved and what problem do you want to solve with that proposal?

**Comment by olemr** [comment]
Just a pointer to how to do it.
Sometimes port 8080 needs to be used for something else.
See also: https://community.openhab.org/t/howto-change-the-default-8080-rest-api-port-for-oh2/46207?u=omr

**Comment by MyRaceData** [comment]
I'm not sure if the configuration section is the appropriate place to mention how to change the port for the REST api because after a quick look, I don't see any mention of the REST api in the configuration section. I do feel it should be noted somewhere how to change the port. Perhaps here in the UI section which describes the REST api:
https://www.openhab.org/docs/configuration/restdocs.html
I remember reading the section of the documentation about the REST api and being a little confused by it as a new user. I intend to give that section another look with an eye toward making it easier for a new user to understand but will add a quick edit about how to change the port now if everyone thinks this is a good location for this information.

**Comment by Confectrician** [comment]
Changing the listening port does not only affect the rest api, but many other parts too.
(Opening PaperUi, Basic UI, url for vscode and ios/android)

So we should find a different place.

I would tag such informatoin as "advanced", so maybe https://www.openhab.org/docs/administration/ is the right area for this.
BUt since there is not really much content yet over there, we shuold think about a general addition of an "advanced configuration" page.
