### ISSUE TITLE
Correct capital first letter for "Item", "Sitemap", ... in ESH articles

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-docs#728]
From the Crowdin glossary by @ThomDietrich 

> openHAB "Sitemap(s)" must not be translated and written with a **capital first letter**

From the items docs site: 

> The following **item** types are currently available (alphabetical order):

What guidline should be followed?

**Comment by mueller-ma** [comment]
Mainly asking because of https://github.com/openhab/openhab-android/pull/932/commits/5d822db75a8f63113a8ff591d699461fd305a159 (https://github.com/openhab/openhab-android/pull/932)

**Comment by ThomDietrich** [comment]
Hey @mueller-ma 👋 

I spent quite some effort to always make sure the documentation *mostly* follows the rule. We decided to do so once and I still think it's a good move.

Now when you say "docs site you are right, it's not enforced in all articles below https://www.openhab.org/docs/concepts Why? Because those articles are imported from the ESH repo. Thanks for noticing ;)

Someone needs to create a PR over there to capitalize all words. (Binding, Thing, Item, Sitemap, ...)

**Comment by Confectrician** [comment]
>Someone needs to create a PR over there to capitalize all words.

Done.

**Comment by Confectrician** [comment]
The smarthome PR for this has been merged.

**Comment by ThomDietrich** [comment]
Nice. Thanks @Confectrician !
