### ISSUE TITLE
Build Error? Transformation Services page looks different on the website

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-docs#803]
Hi,
[this page](https://www.openhab.org/docs/configuration/transformations.html) does not contain the _Available Transformations_ section even though its present here at GitHub in the 2.3.0 tag, in the master branch and in the 2.3-patch branch. Is this an error with the build or did I miss something?

**Comment by ghys** [comment]
That would be because the script preparing the docs has a dirty hack (I know... 😄) and cuts those files explicitely so that those lists of add-ons don't appear - they are in Jekyll syntax and would not compile.
Add-ons are listed at https://www.openhab.org/addons/) and nowhere else. So those sections should be removed eventually and the rest of the content should be moved under "configuration" - that's where they appear on the website.

https://github.com/openhab/website/blob/39cdb0776585737637bf6335494bb5fd46a64f86/prepare-docs.rb#L172

**Comment by pfink** [comment]
Hm, but for me the current "Tranformation Services" section within the configuration page is quite bad... It doesn't even provide a link or a hint where the actual addon documentation with all the details can be found.

**Comment by ghys** [comment]
Then maybe a link to https://www.openhab.org/addons/#transform (which will scroll automatically to the transform addons section) would be enough?

**Comment by pfink** [comment]
Sounds good! Could we also link somehow to "all" addons instead of only the "featured" ones?

**Comment by Confectrician** [comment]
> Could we also link somehow to "all" addons instead of only the "featured" ones?

+1

Definetely makes sense for the frew transformations.
