### ISSUE TITLE
Redirects don't work properly for versioned docs

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-docs#813]
CC @ghys and @kaikreuzer 

It seems that #770 didn't catch all possible cases of redirection.

Example: 
https://docs.openhab.org/v2.1/addons/bindings/chromecast/readme.html

**Comment by ghys** [comment]
If you're talking specifically about the 2.1 docs, they were not migrated
to vuepress because their structure was a little different so the script
didn't work out of the box. Their location under docs.openhab.org is still
valid and they will stay there until we eventually clean them up. 2.2 is
another story!

**Comment by Confectrician** [comment]
I have found the 2.1 docs while googling for the chromecast binding.
2.2 throws a 404.

I will think about a way we can improve this.
