### ISSUE TITLE
Rewrite Introduction section

### ISSUE THREAD

**Issue by LightIsLife** [openhab/openhab-docs#849]
Raising this issue here to keep track of and a link to the related [forum discussion](https://community.openhab.org/t/introduction-in-docs-proposed-rewrite/62772)

I started this topic in the forum with a proposal to an edit/rewrite of the Introduction section of the docs. This attempt has been triggered by many discussion here in the forum to lower the entrance hurdle to the docs. 
Synopsis:
- more entry level for inexperienced users is needed
- proposal needs to address #845 and maybe #838 (but the latter that can also be done at a later point)
- most relevant concepts need to be introduced at a lower and more concise level

Text has been developed in the [forum](https://community.openhab.org/t/introduction-in-docs-proposed-rewrite/62772) and will be transferred into a PR

**Comment by ghys** [comment]
Please note that the introduction.md found in this repo is not the one which is actually displayed on the website at https://www.openhab.org/docs/ - for historical reasons (and because the introduction between the old docs.openhab.org and the new website needed to be different), it is currently here:
https://github.com/openhab/website/blob/master/docs/readme.md

It doesn't prevent you from making changes here (it's actually better!) and we'll get it on the website for sure.

**Comment by ghys** [comment]
@LightIsLife @Confectrician please have a look at the preview here: https://deploy-preview-146--openhab-website.netlify.com/docs/ - there are a number of bad links (e.g. `/concepts/items` where it should be `/concepts/items.html`) which should be addressed before https://github.com/openhab/website/pull/146 is merged.
Also shouldn't there be a mention of the Download page (even a Download button) - this page is linked from the big "Get Started >" button on the home page?
Maybe also add an openHAB logo for fanciness since it's the intro, like before?
```
<h1 class="welcome">Welcome to openHAB!</h1>

<style>
@media (min-width: 720px) {
  .intro-logo {
    margin-left: 3rem; float: right;
  }
}
h1.welcome {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  font-size: 36pt;
}
</style>

<img src="/openhab-logo-square.png" width="200" height="200" class="intro-logo" />
```

**Comment by LightIsLife** [comment]
@ghys thanks for catching the bad links, sorry for that.
Created new PR https://github.com/openhab/openhab-docs/pull/862 
To address all issues (hopefully 😄 )
