### ISSUE TITLE
[Configuration/Items, Concepts/Items] different informations for Items

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-docs#899]
https://www.openhab.org/docs/concepts/items.html and
https://www.openhab.org/docs/configuration/items.html 

have (in parts) sort of same information, but slightly differences (e.g. no Group COUNT in configuration/items.html)

Unfortunately I'm not good enough to fix that properly.

**Comment by Confectrician** [comment]
Maybe you could list the differences a bit more in detail to help me out, since you already recognized some of them.

I am waiting for one of the others to merge #889 und #890, to reintegrate the concepts articles.
After that an improvement of the concepts section is planned anyway, so we can correct those differences aside.

**Comment by Confectrician** [comment]
The articles have been changed many times meanwhile and the only mentioned point "group count" is already available now in the configuration article.

If there are still differences left, we should name them in a new issue and solve this on an up to date base.
