### ISSUE TITLE
Karaf console command and example do not match

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docs#91]
On http://docs.openhab.org/administration/console.html the instructions say:

> If openHAB runs a service, the console can be accessed using ssh to the openHAB host on port 8101. The default Username/Password is openhab/habopen.

However, the provided output of the command shows the user having logged in as user karaf.

> ssh karaf@localhost -p 8101

This should be

ssh openhab@localhost -p 8101

I'd fix it myself but I don't yet know how to have more than one pull request at a time.

**Comment by ThomDietrich** [comment]
Hey @rkoshak, there is no same in that :) You can actually learn quite a lot going through the excellent GitHub Guides https://guides.github.com - have fun!

One pull request is always linked to one branch. A few minutes ago you [already learned](https://github.com/openhab/openhab-docs/pull/89/commits), that commits pushed to a branch will by that also be part of the pull request, which is great for tuning your contribution till it's accepted by the repository maintainers. The solution to what you are wondering is to always create a new branch for a new pull request. You should never commit to or pull-request from the main branch (h-pages in this case).

To now create a second pull request on the issue here create a new branch named "karaf-login" and commit your changes to it. Important! As your gh-pages now has it's own decoupled commits compared to the origin (the repository here), be sure to create the branch based on the latest commit from here!

**Comment by rkoshak** [comment]
Thanks! I'll give that a try tomorrow.
