### ISSUE TITLE
Sitemaps files - guide doesn't say how filename should be saved

### ISSUE THREAD

**Issue by leopheard** [openhab/openhab-docs#997]
Hi all,

This guide is very detailed on the sitemaps:

https://www.openhab.org/docs/configuration/sitemaps.html

but doesn't explain how to save the filename. I've tried default.sitemap or demo.sitemap but none seem to register and the interface tells me to setup a sitemap file?

**Comment by Confectrician** [comment]
Hi,

The filename doesn't need to be in a special naming.

`choosenName.sitemap` should be fine, which includes your examples.

The contents of the file are more important, so maybe there is something wrong with the configured sitemap which prevents it from loading.

**Comment by gitMiguel** [comment]
I think the documentation is sufficient and Jerome sums it up quite nicely. @leopheard can this be closed?

As a side question to @Confectrician, there's quite a lot old or stale issues. Can they be closed? Can I help?

**Comment by Confectrician** [comment]
>I think the documentation is sufficient and Jerome sums it up quite nicely. @leopheard can this be closed?

I think so.

>As a side question to @Confectrician, there's quite a lot old or stale issues. Can they be closed? Can I help?

Any help is welcome.
I also thought about introducing a "stale" label, since documentation has changed heavily over the last years.
So it may be a good idea to reorganize the issues.
If we close a valid one by accident we can still reopen it.

Long story short. Feel free to ping me on issues that should get a stale label and i will add it.
We can then give some time to react on those issues.

**Comment by gitMiguel** [comment]
IMO there are lot's of issues that are beyond stale and could be closed right away. Just thinking that depending on users notification settings they may never get info of this stale label and the obsolete issue stays.
